#============================================================= -*-Perl-*-
#
# Lemplate::Grammar
#
# DESCRIPTION
#   Grammar file for the Template Toolkit language containing token
#   definitions and parser state/rules tables generated by Parse::Yapp.
#
# AUTHOR
#   Ingy döt Net   <ingy@cpan.org>
#
# ORIGINAL AUTHOR
#   Andy Wardley   <abw@kfs.org>
#
# COPYRIGHT
#   Copyright (C) 2006-2008 Ingy döt Net.
#   Copyright (C) 1996-2000 Andy Wardley.
#   Copyright (C) 1998-2000 Canon Research Centre Europe Ltd.
#
#   This module is free software; you can redistribute it and/or
#   modify it under the same terms as Perl itself.
#
#------------------------------------------------------------------------
#
# NOTE: this module is constructed from the parser/Grammar.pm.skel
# file by running the parser/yc script.  You only need to do this if 
# you have modified the grammar in the parser/Parser.yp file and need
# to-recompile it.  See the README in the 'parser' directory for more
# information (sub-directory of the Lemplate distribution).
#
#========================================================================

package Lemplate::Grammar;

require 5.004;

use strict;
use vars qw( $VERSION );

$VERSION  = sprintf("%d.%02d", q$Revision: 2.10 $ =~ /(\d+)\.(\d+)/);

my (@RESERVED, %CMPOP, $LEXTABLE, $RULES, $STATES);
my ($factory, $rawstart);


#========================================================================
# Reserved words, comparison and binary operators
#========================================================================

@RESERVED = qw( 
	GET CALL SET DEFAULT INSERT INCLUDE PROCESS WRAPPER BLOCK END
	USE RAW PLUGIN FILTER MACRO JAVASCRIPT TO STEP AND OR NOT DIV MOD
	IF UNLESS ELSE ELSIF FOR NEXT WHILE SWITCH CASE META IN
	TRY THROW CATCH FINAL LAST RETURN STOP CLEAR VIEW DEBUG
    );

# for historical reasons, != and == are converted to ne and eq to perform 
# stringwise comparison (mainly because it doesn't generate "non-numerical 
# comparison" warnings which != and == can) but the others (e.g. < > <= >=)
# are not converted to their stringwise equivalents.  I added 'gt' et al, 
# briefly for v2.04d and then took them out again in 2.04e.

%CMPOP = qw( 
    != ~=
    == ==
    <  <
    >  >
    >= >=
    <= <=
);


#========================================================================
# Lexer Token Table
#========================================================================

# lookup table used by lexer is initialised with special-cases
$LEXTABLE = {
    'FOREACH' => 'FOR',
    'BREAK'   => 'LAST',
    '&&'      => 'AND',
    '||'      => 'OR',
    '!'       => 'NOT',
    '|'	      => 'FILTER',
    '.'       => 'DOT',
    '_'       => 'CAT',
    '..'      => 'TO',
#    ':'       => 'MACRO',
    '='       => 'ASSIGN',
    '=>'      => 'ASSIGN',
#    '->'      => 'ARROW',
    ','       => 'COMMA',
    '\\'      => 'REF',
    'and'     => 'AND',		# explicitly specified so that qw( and or
    'or'      => 'OR',		# not ) can always be used in lower case, 
    'not'     => 'NOT',		# regardless of ANYCASE flag
    'mod'     => 'MOD',
    'div'     => 'DIV',
};

# localise the temporary variables needed to complete lexer table
{ 
#    my @tokens = qw< ( ) [ ] { } ${ $ / ; : ? >;
    my @tokens = qw< ( ) [ ] { } ${ $ + / ; : ? >;
    my @cmpop  = keys %CMPOP;
#    my @binop  = qw( + - * % );              # '/' above, in @tokens
    my @binop  = qw( - * % );              # '+' and '/' above, in @tokens

    # fill lexer table, slice by slice, with reserved words and operators
    @$LEXTABLE{ @RESERVED, @cmpop, @binop, @tokens } 
	= ( @RESERVED, ('CMPOP') x @cmpop, ('BINOP') x @binop, @tokens );
}


#========================================================================
# CLASS METHODS
#========================================================================

sub new {
    my $class = shift;
    bless {
	LEXTABLE => $LEXTABLE,
	STATES   => $STATES,
	RULES    => $RULES,
    }, $class;
}

# update method to set package-scoped $factory lexical 
sub install_factory {
    my ($self, $new_factory) = @_;
    $factory = $new_factory;
}


#========================================================================
# States
#========================================================================

$STATES = [
	{#State 0
		ACTIONS => {
			'MACRO' => 21,
			'NOT' => 60,
			"(" => 22,
			'INCLUDE' => 62,
			'THROW' => 61,
			"\"" => 20,
			"{" => 56,
			"\${" => 57,
			'DEBUG' => 63,
			"[" => 26,
			'CLEAR' => 27,
			'META' => 65,
			'IF' => 30,
			";" => -19,
			'CALL' => 74,
			'SET' => 73,
			"\$" => 33,
			'NEXT' => 31,
			'VIEW' => 36,
			'USE' => 37,
			'UNLESS' => 3,
			'REF' => 34,
			'WHILE' => 2,
			'GET' => 35,
			'STOP' => 5,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'FOR' => 43,
			'NUMBER' => 10,
			'perl' => 7,
			'RAW' => 39,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'BLOCK' => 46,
			'RETURN' => 48,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'rawperl' => 18,
			'DEFAULT' => 54,
			'SWITCH' => 49,
			'IDENT' => 15,
			'FILTER' => 16,
			'LITERAL' => 50
		},
		DEFAULT => -3,
		GOTOS => {
			'capture' => 11,
			'view' => 47,
			'loop' => 17,
			'template' => 51,
			'atomdir' => 14,
			'use' => 19,
			'sterm' => 53,
			'term' => 55,
			'assign' => 52,
			'node' => 1,
			'switch' => 4,
			'directive' => 6,
			'macro' => 38,
			'wrapper' => 8,
			'item' => 40,
			'filter' => 69,
			'chunks' => 68,
			'defblockname' => 67,
			'defblock' => 29,
			'condition' => 71,
			'expr' => 32,
			'try' => 70,
			'lterm' => 72,
			'statement' => 75,
			'javascript' => 58,
			'setlist' => 23,
			'chunk' => 59,
			'block' => 64,
			'atomexpr' => 25,
			'anonblock' => 24,
			'ident' => 28,
			'raw' => 66
		}
	},
	{#State 1
		DEFAULT => -128
	},
	{#State 2
		ACTIONS => {
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78,
			"\$" => 33,
			'NUMBER' => 10,
			"{" => 56,
			'REF' => 34,
			"\"" => 20,
			"\${" => 57,
			'NOT' => 60,
			"(" => 22
		},
		GOTOS => {
			'lterm' => 72,
			'item' => 40,
			'ident' => 77,
			'sterm' => 53,
			'term' => 55,
			'node' => 1,
			'expr' => 76
		}
	},
	{#State 3
		ACTIONS => {
			'NOT' => 60,
			"(" => 22,
			'REF' => 34,
			"\"" => 20,
			"{" => 56,
			"\${" => 57,
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78
		},
		GOTOS => {
			'term' => 55,
			'sterm' => 53,
			'ident' => 77,
			'item' => 40,
			'lterm' => 72,
			'expr' => 79,
			'node' => 1
		}
	},
	{#State 4
		DEFAULT => -23
	},
	{#State 5
		DEFAULT => -39
	},
	{#State 6
		DEFAULT => -8
	},
	{#State 7
		DEFAULT => -27
	},
	{#State 8
		DEFAULT => -44
	},
	{#State 9
		ACTIONS => {
			'FILENAME' => 90,
			'LITERAL' => 80,
			'IDENT' => 83,
			"\"" => 89,
			'NUMBER' => 84,
			"\$" => 88
		},
		GOTOS => {
			'names' => 86,
			'name' => 85,
			'filename' => 87,
			'nameargs' => 82,
			'filepart' => 81
		}
	},
	{#State 10
		DEFAULT => -114
	},
	{#State 11
		DEFAULT => -11
	},
	{#State 12
		ACTIONS => {
			"\$" => 88,
			'NUMBER' => 84,
			'IDENT' => 83,
			"\"" => 89,
			'LITERAL' => 80,
			'FILENAME' => 90
		},
		GOTOS => {
			'nameargs' => 91,
			'filepart' => 81,
			'name' => 85,
			'names' => 86,
			'filename' => 87
		}
	},
	{#State 13
		ACTIONS => {
			'NUMBER' => 84,
			"\$" => 88,
			'FILENAME' => 90,
			'LITERAL' => 80,
			"\"" => 89,
			'IDENT' => 83
		},
		GOTOS => {
			'filepart' => 81,
			'nameargs' => 92,
			'names' => 86,
			'name' => 85,
			'filename' => 87
		}
	},
	{#State 14
		ACTIONS => {
			";" => -21
		},
		DEFAULT => -29
	},
	{#State 15
		DEFAULT => -131
	},
	{#State 16
		ACTIONS => {
			"\$" => 93,
			'NUMBER' => 84,
			'IDENT' => 96,
			"\"" => 94,
			'FILENAME' => 90,
			'LITERAL' => 98,
			"\${" => 57
		},
		GOTOS => {
			'filepart' => 81,
			'lnameargs' => 95,
			'names' => 86,
			'name' => 85,
			'lvalue' => 97,
			'nameargs' => 100,
			'filename' => 87,
			'item' => 99
		}
	},
	{#State 17
		DEFAULT => -24
	},
	{#State 18
		DEFAULT => -16
	},
	{#State 19
		DEFAULT => -13
	},
	{#State 20
		DEFAULT => -177,
		GOTOS => {
			'quoted' => 101
		}
	},
	{#State 21
		ACTIONS => {
			'IDENT' => 102
		}
	},
	{#State 22
		ACTIONS => {
			"(" => 22,
			'NOT' => 60,
			"{" => 56,
			'REF' => 34,
			"\"" => 20,
			"\${" => 57,
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			'LITERAL' => 50,
			"[" => 26
		},
		GOTOS => {
			'node' => 1,
			'term' => 55,
			'sterm' => 53,
			'lterm' => 72,
			'ident' => 104,
			'item' => 40,
			'assign' => 105,
			'expr' => 103
		}
	},
	{#State 23
		ACTIONS => {
			"\${" => 57,
			'LITERAL' => 107,
			'IDENT' => 15,
			'COMMA' => 106,
			"\$" => 33
		},
		DEFAULT => -20,
		GOTOS => {
			'ident' => 109,
			'item' => 40,
			'assign' => 108,
			'node' => 1
		}
	},
	{#State 24
		DEFAULT => -10
	},
	{#State 25
		ACTIONS => {
			'WHILE' => 112,
			'UNLESS' => 113,
			'FILTER' => 111,
			'WRAPPER' => 110,
			'FOR' => 115,
			'IF' => 114
		}
	},
	{#State 26
		ACTIONS => {
			"\${" => 57,
			'REF' => 34,
			"{" => 56,
			"\"" => 20,
			'NUMBER' => 10,
			"\$" => 33,
			'LITERAL' => 78,
			"[" => 26,
			"]" => 118,
			'IDENT' => 15
		},
		GOTOS => {
			'node' => 1,
			'list' => 117,
			'range' => 116,
			'ident' => 77,
			'lterm' => 72,
			'item' => 40,
			'sterm' => 120,
			'term' => 119
		}
	},
	{#State 27
		DEFAULT => -40
	},
	{#State 28
		ACTIONS => {
			'DOT' => 121,
			'ASSIGN' => 122
		},
		DEFAULT => -110
	},
	{#State 29
		DEFAULT => -9
	},
	{#State 30
		ACTIONS => {
			'NOT' => 60,
			"(" => 22,
			"\${" => 57,
			"{" => 56,
			'REF' => 34,
			"\"" => 20,
			'NUMBER' => 10,
			"\$" => 33,
			'LITERAL' => 78,
			"[" => 26,
			'IDENT' => 15
		},
		GOTOS => {
			'expr' => 123,
			'node' => 1,
			'term' => 55,
			'sterm' => 53,
			'ident' => 77,
			'item' => 40,
			'lterm' => 72
		}
	},
	{#State 31
		DEFAULT => -42
	},
	{#State 32
		ACTIONS => {
			'CAT' => 127,
			'MOD' => 131,
			"+" => 128,
			'OR' => 130,
			'AND' => 133,
			";" => -17,
			'DIV' => 126,
			'CMPOP' => 129,
			"/" => 125,
			"?" => 124,
			'BINOP' => 132
		},
		DEFAULT => -28
	},
	{#State 33
		ACTIONS => {
			'IDENT' => 134
		}
	},
	{#State 34
		ACTIONS => {
			"\${" => 57,
			'IDENT' => 15,
			"\$" => 33
		},
		GOTOS => {
			'ident' => 135,
			'item' => 40,
			'node' => 1
		}
	},
	{#State 35
		ACTIONS => {
			'IDENT' => 15,
			'LITERAL' => 78,
			"[" => 26,
			"\$" => 33,
			'NUMBER' => 10,
			"\"" => 20,
			'REF' => 34,
			"{" => 56,
			"\${" => 57,
			'NOT' => 60,
			"(" => 22
		},
		GOTOS => {
			'sterm' => 53,
			'term' => 55,
			'lterm' => 72,
			'ident' => 77,
			'item' => 40,
			'expr' => 136,
			'node' => 1
		}
	},
	{#State 36
		ACTIONS => {
			'FILENAME' => 90,
			'LITERAL' => 80,
			"\"" => 89,
			'IDENT' => 83,
			'NUMBER' => 84,
			"\$" => 88
		},
		GOTOS => {
			'filename' => 87,
			'names' => 86,
			'name' => 85,
			'filepart' => 81,
			'nameargs' => 137
		}
	},
	{#State 37
		ACTIONS => {
			'NUMBER' => 84,
			"\$" => 93,
			'LITERAL' => 98,
			'FILENAME' => 90,
			"\${" => 57,
			'IDENT' => 96,
			"\"" => 94
		},
		GOTOS => {
			'name' => 85,
			'names' => 86,
			'lnameargs' => 138,
			'filepart' => 81,
			'item' => 99,
			'filename' => 87,
			'nameargs' => 100,
			'lvalue' => 97
		}
	},
	{#State 38
		DEFAULT => -12
	},
	{#State 39
		ACTIONS => {
			"\${" => 57,
			'FILENAME' => 90,
			'LITERAL' => 98,
			"\"" => 94,
			'IDENT' => 96,
			'NUMBER' => 84,
			"\$" => 93
		},
		GOTOS => {
			'filename' => 87,
			'item' => 99,
			'lvalue' => 97,
			'nameargs' => 100,
			'lnameargs' => 139,
			'names' => 86,
			'name' => 85,
			'filepart' => 81
		}
	},
	{#State 40
		ACTIONS => {
			"(" => 140
		},
		DEFAULT => -129
	},
	{#State 41
		DEFAULT => -41
	},
	{#State 42
		DEFAULT => -6
	},
	{#State 43
		ACTIONS => {
			"[" => 26,
			'LITERAL' => 78,
			'IDENT' => 141,
			'NUMBER' => 10,
			"\$" => 33,
			"\${" => 57,
			"{" => 56,
			'REF' => 34,
			"\"" => 20
		},
		GOTOS => {
			'item' => 40,
			'ident' => 77,
			'loopvar' => 143,
			'lterm' => 72,
			'term' => 142,
			'sterm' => 53,
			'node' => 1
		}
	},
	{#State 44
		ACTIONS => {
			";" => 144
		}
	},
	{#State 45
		ACTIONS => {
			";" => 145
		}
	},
	{#State 46
		ACTIONS => {
			'FILENAME' => 90,
			'LITERAL' => 151,
			'IDENT' => 149,
			'NUMBER' => 84
		},
		DEFAULT => -88,
		GOTOS => {
			'filepart' => 81,
			'blockname' => 150,
			'meta' => 146,
			'metadata' => 152,
			'filename' => 148,
			'blockargs' => 147
		}
	},
	{#State 47
		DEFAULT => -15
	},
	{#State 48
		DEFAULT => -38
	},
	{#State 49
		ACTIONS => {
			"[" => 26,
			'LITERAL' => 78,
			'IDENT' => 15,
			'NUMBER' => 10,
			"\$" => 33,
			"\${" => 57,
			"\"" => 20,
			"{" => 56,
			'REF' => 34,
			'NOT' => 60,
			"(" => 22
		},
		GOTOS => {
			'expr' => 153,
			'node' => 1,
			'sterm' => 53,
			'term' => 55,
			'item' => 40,
			'ident' => 77,
			'lterm' => 72
		}
	},
	{#State 50
		ACTIONS => {
			'ASSIGN' => 154
		},
		DEFAULT => -113
	},
	{#State 51
		ACTIONS => {
			'' => 155
		}
	},
	{#State 52
		DEFAULT => -150
	},
	{#State 53
		DEFAULT => -105
	},
	{#State 54
		ACTIONS => {
			"\$" => 33,
			'IDENT' => 15,
			"\${" => 57,
			'LITERAL' => 107
		},
		GOTOS => {
			'node' => 1,
			'assign' => 52,
			'ident' => 109,
			'item' => 40,
			'setlist' => 156
		}
	},
	{#State 55
		DEFAULT => -147
	},
	{#State 56
		ACTIONS => {
			"\$" => 33,
			"\${" => 57,
			'LITERAL' => 160,
			'IDENT' => 15
		},
		DEFAULT => -120,
		GOTOS => {
			'param' => 159,
			'params' => 158,
			'item' => 161,
			'hash' => 157
		}
	},
	{#State 57
		ACTIONS => {
			'REF' => 34,
			'IDENT' => 15,
			"\"" => 20,
			'LITERAL' => 78,
			"\${" => 57,
			"\$" => 33,
			'NUMBER' => 10
		},
		GOTOS => {
			'sterm' => 162,
			'ident' => 77,
			'item' => 40,
			'node' => 1
		}
	},
	{#State 58
		DEFAULT => -26
	},
	{#State 59
		DEFAULT => -5
	},
	{#State 60
		ACTIONS => {
			"(" => 22,
			'NOT' => 60,
			"\${" => 57,
			'REF' => 34,
			"{" => 56,
			"\"" => 20,
			'NUMBER' => 10,
			"\$" => 33,
			"[" => 26,
			'LITERAL' => 78,
			'IDENT' => 15
		},
		GOTOS => {
			'node' => 1,
			'expr' => 163,
			'lterm' => 72,
			'item' => 40,
			'ident' => 77,
			'sterm' => 53,
			'term' => 55
		}
	},
	{#State 61
		ACTIONS => {
			'LITERAL' => 80,
			'FILENAME' => 90,
			'IDENT' => 83,
			"\"" => 89,
			'NUMBER' => 84,
			"\$" => 88
		},
		GOTOS => {
			'filename' => 87,
			'name' => 85,
			'names' => 86,
			'filepart' => 81,
			'nameargs' => 164
		}
	},
	{#State 62
		ACTIONS => {
			'FILENAME' => 90,
			'LITERAL' => 80,
			"\"" => 89,
			'IDENT' => 83,
			'NUMBER' => 84,
			"\$" => 88
		},
		GOTOS => {
			'name' => 85,
			'names' => 86,
			'filename' => 87,
			'filepart' => 81,
			'nameargs' => 165
		}
	},
	{#State 63
		ACTIONS => {
			"\$" => 88,
			'NUMBER' => 84,
			'IDENT' => 83,
			"\"" => 89,
			'LITERAL' => 80,
			'FILENAME' => 90
		},
		GOTOS => {
			'filename' => 87,
			'name' => 85,
			'names' => 86,
			'filepart' => 81,
			'nameargs' => 166
		}
	},
	{#State 64
		DEFAULT => -1
	},
	{#State 65
		ACTIONS => {
			'IDENT' => 168
		},
		GOTOS => {
			'meta' => 146,
			'metadata' => 167
		}
	},
	{#State 66
		DEFAULT => -14
	},
	{#State 67
		ACTIONS => {
			'IDENT' => 168
		},
		DEFAULT => -88,
		GOTOS => {
			'meta' => 146,
			'metadata' => 152,
			'blockargs' => 169
		}
	},
	{#State 68
		ACTIONS => {
			'perl' => 7,
			'RAW' => 39,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'FOR' => 43,
			'NUMBER' => 10,
			'REF' => 34,
			'UNLESS' => 3,
			'WHILE' => 2,
			'GET' => 35,
			'STOP' => 5,
			'USE' => 37,
			'VIEW' => 36,
			'SWITCH' => 49,
			'IDENT' => 15,
			'LITERAL' => 50,
			'FILTER' => 16,
			'rawperl' => 18,
			'DEFAULT' => 54,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'INSERT' => 12,
			'BLOCK' => 46,
			'WRAPPER' => 13,
			'RETURN' => 48,
			'DEBUG' => 63,
			"[" => 26,
			'META' => 65,
			'CLEAR' => 27,
			"{" => 56,
			"\"" => 20,
			"\${" => 57,
			'MACRO' => 21,
			'NOT' => 60,
			"(" => 22,
			'THROW' => 61,
			'INCLUDE' => 62,
			'NEXT' => 31,
			";" => -19,
			"\$" => 33,
			'CALL' => 74,
			'SET' => 73,
			'IF' => 30
		},
		DEFAULT => -2,
		GOTOS => {
			'defblockname' => 67,
			'capture' => 11,
			'filter' => 69,
			'view' => 47,
			'defblock' => 29,
			'atomdir' => 14,
			'try' => 70,
			'condition' => 71,
			'expr' => 32,
			'loop' => 17,
			'statement' => 75,
			'lterm' => 72,
			'assign' => 52,
			'term' => 55,
			'sterm' => 53,
			'use' => 19,
			'switch' => 4,
			'node' => 1,
			'javascript' => 58,
			'chunk' => 170,
			'macro' => 38,
			'setlist' => 23,
			'directive' => 6,
			'anonblock' => 24,
			'atomexpr' => 25,
			'wrapper' => 8,
			'raw' => 66,
			'ident' => 28,
			'item' => 40
		}
	},
	{#State 69
		DEFAULT => -45
	},
	{#State 70
		DEFAULT => -25
	},
	{#State 71
		DEFAULT => -22
	},
	{#State 72
		DEFAULT => -104
	},
	{#State 73
		ACTIONS => {
			'IDENT' => 15,
			'LITERAL' => 107,
			"\${" => 57,
			"\$" => 33
		},
		GOTOS => {
			'item' => 40,
			'ident' => 109,
			'assign' => 52,
			'setlist' => 171,
			'node' => 1
		}
	},
	{#State 74
		ACTIONS => {
			'NUMBER' => 10,
			"\$" => 33,
			"[" => 26,
			'LITERAL' => 78,
			'IDENT' => 15,
			"(" => 22,
			'NOT' => 60,
			"\${" => 57,
			"\"" => 20,
			"{" => 56,
			'REF' => 34
		},
		GOTOS => {
			'ident' => 77,
			'lterm' => 72,
			'item' => 40,
			'term' => 55,
			'sterm' => 53,
			'node' => 1,
			'expr' => 172
		}
	},
	{#State 75
		ACTIONS => {
			";" => 173
		}
	},
	{#State 76
		ACTIONS => {
			'CMPOP' => 129,
			"/" => 125,
			'CAT' => 127,
			"+" => 128,
			"?" => 124,
			'MOD' => 131,
			'OR' => 130,
			'AND' => 133,
			'BINOP' => 132,
			'DIV' => 126,
			";" => 174
		}
	},
	{#State 77
		ACTIONS => {
			'DOT' => 121
		},
		DEFAULT => -110
	},
	{#State 78
		DEFAULT => -113
	},
	{#State 79
		ACTIONS => {
			'OR' => 130,
			'AND' => 133,
			'BINOP' => 132,
			'DIV' => 126,
			";" => 175,
			'CMPOP' => 129,
			"/" => 125,
			'CAT' => 127,
			"+" => 128,
			'MOD' => 131,
			"?" => 124
		}
	},
	{#State 80
		DEFAULT => -170
	},
	{#State 81
		DEFAULT => -172
	},
	{#State 82
		DEFAULT => -36
	},
	{#State 83
		DEFAULT => -174
	},
	{#State 84
		DEFAULT => -175
	},
	{#State 85
		DEFAULT => -167
	},
	{#State 86
		ACTIONS => {
			"+" => 177,
			"(" => 176
		},
		DEFAULT => -157,
		GOTOS => {
			'args' => 178
		}
	},
	{#State 87
		ACTIONS => {
			'DOT' => 179
		},
		DEFAULT => -169
	},
	{#State 88
		ACTIONS => {
			'IDENT' => 15,
			"\${" => 57,
			"\$" => 33
		},
		GOTOS => {
			'node' => 1,
			'item' => 40,
			'ident' => 180
		}
	},
	{#State 89
		DEFAULT => -177,
		GOTOS => {
			'quoted' => 181
		}
	},
	{#State 90
		DEFAULT => -173
	},
	{#State 91
		DEFAULT => -34
	},
	{#State 92
		ACTIONS => {
			";" => 182
		}
	},
	{#State 93
		ACTIONS => {
			'IDENT' => 183,
			"\${" => 57,
			"\$" => 33
		},
		GOTOS => {
			'ident' => 180,
			'item' => 40,
			'node' => 1
		}
	},
	{#State 94
		DEFAULT => -177,
		GOTOS => {
			'quoted' => 184
		}
	},
	{#State 95
		ACTIONS => {
			";" => 185
		}
	},
	{#State 96
		ACTIONS => {
			'ASSIGN' => -131
		},
		DEFAULT => -174
	},
	{#State 97
		ACTIONS => {
			'ASSIGN' => 186
		}
	},
	{#State 98
		ACTIONS => {
			'ASSIGN' => -162
		},
		DEFAULT => -170
	},
	{#State 99
		DEFAULT => -160
	},
	{#State 100
		DEFAULT => -159
	},
	{#State 101
		ACTIONS => {
			";" => 188,
			'TEXT' => 187,
			"\$" => 33,
			"\${" => 57,
			'IDENT' => 15,
			"\"" => 191
		},
		GOTOS => {
			'item' => 40,
			'ident' => 190,
			'node' => 1,
			'quotable' => 189
		}
	},
	{#State 102
		ACTIONS => {
			'NEXT' => 31,
			'SET' => 73,
			'CALL' => 74,
			"\$" => 33,
			'IF' => 30,
			'DEBUG' => 63,
			'CLEAR' => 27,
			"[" => 26,
			"{" => 56,
			"\"" => 20,
			"\${" => 57,
			'INCLUDE' => 62,
			'THROW' => 61,
			"(" => 195,
			'NOT' => 60,
			'SWITCH' => 49,
			'IDENT' => 15,
			'LITERAL' => 50,
			'FILTER' => 16,
			'DEFAULT' => 54,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'BLOCK' => 196,
			'RETURN' => 48,
			'perl' => 7,
			'PROCESS' => 9,
			'LAST' => 41,
			'NUMBER' => 10,
			'FOR' => 43,
			'GET' => 35,
			'WHILE' => 2,
			'REF' => 34,
			'UNLESS' => 3,
			'STOP' => 5
		},
		GOTOS => {
			'filter' => 69,
			'mdir' => 194,
			'condition' => 71,
			'loop' => 17,
			'expr' => 193,
			'try' => 70,
			'atomdir' => 14,
			'term' => 55,
			'sterm' => 53,
			'assign' => 52,
			'lterm' => 72,
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'setlist' => 23,
			'directive' => 192,
			'wrapper' => 8,
			'atomexpr' => 25,
			'item' => 40,
			'ident' => 104
		}
	},
	{#State 103
		ACTIONS => {
			"?" => 124,
			'MOD' => 131,
			"+" => 128,
			'CAT' => 127,
			"/" => 125,
			'CMPOP' => 129,
			'DIV' => 126,
			'BINOP' => 132,
			'AND' => 133,
			")" => 197,
			'OR' => 130
		}
	},
	{#State 104
		ACTIONS => {
			'DOT' => 121,
			'ASSIGN' => 198
		},
		DEFAULT => -110
	},
	{#State 105
		ACTIONS => {
			")" => 199
		}
	},
	{#State 106
		DEFAULT => -149
	},
	{#State 107
		ACTIONS => {
			'ASSIGN' => 154
		}
	},
	{#State 108
		DEFAULT => -148
	},
	{#State 109
		ACTIONS => {
			'DOT' => 121,
			'ASSIGN' => 198
		}
	},
	{#State 110
		ACTIONS => {
			'NUMBER' => 84,
			"\$" => 88,
			'LITERAL' => 80,
			'FILENAME' => 90,
			"\"" => 89,
			'IDENT' => 83
		},
		GOTOS => {
			'names' => 86,
			'name' => 85,
			'filename' => 87,
			'filepart' => 81,
			'nameargs' => 200
		}
	},
	{#State 111
		ACTIONS => {
			'NUMBER' => 84,
			"\$" => 93,
			'LITERAL' => 98,
			"\${" => 57,
			'FILENAME' => 90,
			"\"" => 94,
			'IDENT' => 96
		},
		GOTOS => {
			'name' => 85,
			'names' => 86,
			'lnameargs' => 201,
			'filepart' => 81,
			'item' => 99,
			'filename' => 87,
			'nameargs' => 100,
			'lvalue' => 97
		}
	},
	{#State 112
		ACTIONS => {
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			'LITERAL' => 78,
			"[" => 26,
			'NOT' => 60,
			"(" => 22,
			"{" => 56,
			'REF' => 34,
			"\"" => 20,
			"\${" => 57
		},
		GOTOS => {
			'item' => 40,
			'ident' => 77,
			'lterm' => 72,
			'term' => 55,
			'sterm' => 53,
			'node' => 1,
			'expr' => 202
		}
	},
	{#State 113
		ACTIONS => {
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78,
			'NOT' => 60,
			"(" => 22,
			'REF' => 34,
			"{" => 56,
			"\"" => 20,
			"\${" => 57
		},
		GOTOS => {
			'sterm' => 53,
			'term' => 55,
			'lterm' => 72,
			'ident' => 77,
			'item' => 40,
			'expr' => 203,
			'node' => 1
		}
	},
	{#State 114
		ACTIONS => {
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78,
			'NOT' => 60,
			"(" => 22,
			"{" => 56,
			'REF' => 34,
			"\"" => 20,
			"\${" => 57
		},
		GOTOS => {
			'sterm' => 53,
			'term' => 55,
			'lterm' => 72,
			'item' => 40,
			'ident' => 77,
			'expr' => 204,
			'node' => 1
		}
	},
	{#State 115
		ACTIONS => {
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 141,
			"[" => 26,
			'LITERAL' => 78,
			'REF' => 34,
			"\"" => 20,
			"{" => 56,
			"\${" => 57
		},
		GOTOS => {
			'node' => 1,
			'term' => 142,
			'sterm' => 53,
			'ident' => 77,
			'loopvar' => 205,
			'item' => 40,
			'lterm' => 72
		}
	},
	{#State 116
		ACTIONS => {
			"]" => 206
		}
	},
	{#State 117
		ACTIONS => {
			"\$" => 33,
			'NUMBER' => 10,
			'COMMA' => 209,
			'IDENT' => 15,
			"]" => 208,
			'LITERAL' => 78,
			"[" => 26,
			'REF' => 34,
			"{" => 56,
			"\"" => 20,
			"\${" => 57
		},
		GOTOS => {
			'item' => 40,
			'lterm' => 72,
			'ident' => 77,
			'sterm' => 53,
			'term' => 207,
			'node' => 1
		}
	},
	{#State 118
		DEFAULT => -108
	},
	{#State 119
		DEFAULT => -117
	},
	{#State 120
		ACTIONS => {
			'TO' => 210
		},
		DEFAULT => -105
	},
	{#State 121
		ACTIONS => {
			'NUMBER' => 212,
			"\$" => 33,
			"\${" => 57,
			'IDENT' => 15
		},
		GOTOS => {
			'node' => 211,
			'item' => 40
		}
	},
	{#State 122
		ACTIONS => {
			'FOR' => 43,
			'NUMBER' => 10,
			'LAST' => 41,
			'PROCESS' => 9,
			'perl' => 7,
			'STOP' => 5,
			'UNLESS' => 3,
			'WHILE' => 2,
			'REF' => 34,
			'GET' => 35,
			'DEFAULT' => 54,
			'FILTER' => 16,
			'LITERAL' => 50,
			'IDENT' => 15,
			'SWITCH' => 49,
			'RETURN' => 48,
			'WRAPPER' => 13,
			'BLOCK' => 196,
			'INSERT' => 12,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			"[" => 26,
			'CLEAR' => 27,
			'DEBUG' => 63,
			"(" => 22,
			'NOT' => 60,
			'INCLUDE' => 62,
			'THROW' => 61,
			"\${" => 57,
			"\"" => 20,
			"{" => 56,
			'CALL' => 74,
			'SET' => 73,
			"\$" => 33,
			'NEXT' => 31,
			'IF' => 30
		},
		GOTOS => {
			'mdir' => 213,
			'filter' => 69,
			'assign' => 52,
			'lterm' => 72,
			'term' => 55,
			'sterm' => 53,
			'try' => 70,
			'atomdir' => 14,
			'condition' => 71,
			'expr' => 214,
			'loop' => 17,
			'directive' => 192,
			'setlist' => 23,
			'node' => 1,
			'switch' => 4,
			'javascript' => 58,
			'item' => 40,
			'ident' => 104,
			'atomexpr' => 25,
			'wrapper' => 8
		}
	},
	{#State 123
		ACTIONS => {
			'CMPOP' => 129,
			"/" => 125,
			'CAT' => 127,
			"+" => 128,
			'MOD' => 131,
			"?" => 124,
			'OR' => 130,
			'AND' => 133,
			'BINOP' => 132,
			'DIV' => 126,
			";" => 215
		}
	},
	{#State 124
		ACTIONS => {
			'LITERAL' => 78,
			"[" => 26,
			'IDENT' => 15,
			'NUMBER' => 10,
			"\$" => 33,
			"\${" => 57,
			'REF' => 34,
			"\"" => 20,
			"{" => 56,
			"(" => 22,
			'NOT' => 60
		},
		GOTOS => {
			'ident' => 77,
			'lterm' => 72,
			'item' => 40,
			'term' => 55,
			'sterm' => 53,
			'node' => 1,
			'expr' => 216
		}
	},
	{#State 125
		ACTIONS => {
			'LITERAL' => 78,
			"[" => 26,
			'IDENT' => 15,
			'NUMBER' => 10,
			"\$" => 33,
			"\${" => 57,
			"{" => 56,
			"\"" => 20,
			'REF' => 34,
			'NOT' => 60,
			"(" => 22
		},
		GOTOS => {
			'expr' => 217,
			'node' => 1,
			'term' => 55,
			'sterm' => 53,
			'lterm' => 72,
			'ident' => 77,
			'item' => 40
		}
	},
	{#State 126
		ACTIONS => {
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			'LITERAL' => 78,
			"[" => 26,
			'NOT' => 60,
			"(" => 22,
			'REF' => 34,
			"{" => 56,
			"\"" => 20,
			"\${" => 57
		},
		GOTOS => {
			'node' => 1,
			'expr' => 218,
			'lterm' => 72,
			'ident' => 77,
			'item' => 40,
			'term' => 55,
			'sterm' => 53
		}
	},
	{#State 127
		ACTIONS => {
			"(" => 22,
			'NOT' => 60,
			"\${" => 57,
			"\"" => 20,
			'REF' => 34,
			"{" => 56,
			'NUMBER' => 10,
			"\$" => 33,
			'LITERAL' => 78,
			"[" => 26,
			'IDENT' => 15
		},
		GOTOS => {
			'node' => 1,
			'expr' => 219,
			'item' => 40,
			'ident' => 77,
			'lterm' => 72,
			'sterm' => 53,
			'term' => 55
		}
	},
	{#State 128
		ACTIONS => {
			'REF' => 34,
			"{" => 56,
			"\"" => 20,
			"\${" => 57,
			"(" => 22,
			'NOT' => 60,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78,
			"\$" => 33,
			'NUMBER' => 10
		},
		GOTOS => {
			'expr' => 220,
			'node' => 1,
			'term' => 55,
			'sterm' => 53,
			'item' => 40,
			'lterm' => 72,
			'ident' => 77
		}
	},
	{#State 129
		ACTIONS => {
			"(" => 22,
			'NOT' => 60,
			"\${" => 57,
			'REF' => 34,
			"\"" => 20,
			"{" => 56,
			'NUMBER' => 10,
			"\$" => 33,
			'LITERAL' => 78,
			"[" => 26,
			'IDENT' => 15
		},
		GOTOS => {
			'term' => 55,
			'sterm' => 53,
			'lterm' => 72,
			'item' => 40,
			'ident' => 77,
			'expr' => 221,
			'node' => 1
		}
	},
	{#State 130
		ACTIONS => {
			"(" => 22,
			'NOT' => 60,
			"\"" => 20,
			"{" => 56,
			'REF' => 34,
			"\${" => 57,
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78
		},
		GOTOS => {
			'item' => 40,
			'ident' => 77,
			'lterm' => 72,
			'sterm' => 53,
			'term' => 55,
			'node' => 1,
			'expr' => 222
		}
	},
	{#State 131
		ACTIONS => {
			"\"" => 20,
			"{" => 56,
			'REF' => 34,
			"\${" => 57,
			'NOT' => 60,
			"(" => 22,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78,
			"\$" => 33,
			'NUMBER' => 10
		},
		GOTOS => {
			'ident' => 77,
			'item' => 40,
			'lterm' => 72,
			'sterm' => 53,
			'term' => 55,
			'node' => 1,
			'expr' => 223
		}
	},
	{#State 132
		ACTIONS => {
			'LITERAL' => 78,
			"[" => 26,
			'IDENT' => 15,
			'NUMBER' => 10,
			"\$" => 33,
			"\${" => 57,
			"{" => 56,
			"\"" => 20,
			'REF' => 34,
			"(" => 22,
			'NOT' => 60
		},
		GOTOS => {
			'expr' => 224,
			'node' => 1,
			'term' => 55,
			'sterm' => 53,
			'ident' => 77,
			'lterm' => 72,
			'item' => 40
		}
	},
	{#State 133
		ACTIONS => {
			'NUMBER' => 10,
			"\$" => 33,
			'LITERAL' => 78,
			"[" => 26,
			'IDENT' => 15,
			'NOT' => 60,
			"(" => 22,
			"\${" => 57,
			"{" => 56,
			'REF' => 34,
			"\"" => 20
		},
		GOTOS => {
			'expr' => 225,
			'node' => 1,
			'sterm' => 53,
			'term' => 55,
			'lterm' => 72,
			'item' => 40,
			'ident' => 77
		}
	},
	{#State 134
		DEFAULT => -133
	},
	{#State 135
		ACTIONS => {
			'DOT' => 121
		},
		DEFAULT => -111
	},
	{#State 136
		ACTIONS => {
			'DIV' => 126,
			'AND' => 133,
			'OR' => 130,
			"+" => 128,
			'MOD' => 131,
			'CAT' => 127,
			'BINOP' => 132,
			"?" => 124,
			"/" => 125,
			'CMPOP' => 129
		},
		DEFAULT => -30
	},
	{#State 137
		ACTIONS => {
			";" => 226
		}
	},
	{#State 138
		DEFAULT => -75
	},
	{#State 139
		DEFAULT => -76
	},
	{#State 140
		DEFAULT => -157,
		GOTOS => {
			'args' => 227
		}
	},
	{#State 141
		ACTIONS => {
			'IN' => 228,
			'ASSIGN' => 229
		},
		DEFAULT => -131
	},
	{#State 142
		DEFAULT => -157,
		GOTOS => {
			'args' => 230
		}
	},
	{#State 143
		ACTIONS => {
			";" => 231
		}
	},
	{#State 144
		ACTIONS => {
			";" => -19,
			'SET' => 73,
			"\$" => 33,
			'CALL' => 74,
			'NEXT' => 31,
			'IF' => 30,
			'DEBUG' => 63,
			"[" => 26,
			'META' => 65,
			'CLEAR' => 27,
			'MACRO' => 21,
			'NOT' => 60,
			"(" => 22,
			'THROW' => 61,
			'INCLUDE' => 62,
			"{" => 56,
			"\"" => 20,
			"\${" => 57,
			'rawperl' => 18,
			'DEFAULT' => 54,
			'IDENT' => 15,
			'SWITCH' => 49,
			'LITERAL' => 50,
			'FILTER' => 16,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'BLOCK' => 46,
			'RETURN' => 48,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'FOR' => 43,
			'NUMBER' => 10,
			'perl' => 7,
			'RAW' => 39,
			'VIEW' => 36,
			'USE' => 37,
			'UNLESS' => 3,
			'REF' => 34,
			'WHILE' => 2,
			'GET' => 35,
			'STOP' => 5
		},
		DEFAULT => -3,
		GOTOS => {
			'item' => 40,
			'ident' => 28,
			'raw' => 66,
			'wrapper' => 8,
			'atomexpr' => 25,
			'anonblock' => 24,
			'block' => 232,
			'setlist' => 23,
			'directive' => 6,
			'macro' => 38,
			'chunk' => 59,
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'sterm' => 53,
			'use' => 19,
			'term' => 55,
			'assign' => 52,
			'lterm' => 72,
			'statement' => 75,
			'expr' => 32,
			'loop' => 17,
			'condition' => 71,
			'try' => 70,
			'atomdir' => 14,
			'defblock' => 29,
			'view' => 47,
			'filter' => 69,
			'capture' => 11,
			'defblockname' => 67,
			'chunks' => 68
		}
	},
	{#State 145
		DEFAULT => -79,
		GOTOS => {
			'@4-2' => 233
		}
	},
	{#State 146
		DEFAULT => -100
	},
	{#State 147
		ACTIONS => {
			";" => 234
		}
	},
	{#State 148
		ACTIONS => {
			'DOT' => 179
		},
		DEFAULT => -85
	},
	{#State 149
		ACTIONS => {
			'ASSIGN' => 235
		},
		DEFAULT => -174
	},
	{#State 150
		DEFAULT => -84
	},
	{#State 151
		DEFAULT => -86
	},
	{#State 152
		ACTIONS => {
			'IDENT' => 168,
			'COMMA' => 236
		},
		DEFAULT => -87,
		GOTOS => {
			'meta' => 237
		}
	},
	{#State 153
		ACTIONS => {
			"/" => 125,
			'CMPOP' => 129,
			"+" => 128,
			"?" => 124,
			'MOD' => 131,
			'CAT' => 127,
			'OR' => 130,
			'DIV' => 126,
			";" => 238,
			'AND' => 133,
			'BINOP' => 132
		}
	},
	{#State 154
		ACTIONS => {
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78,
			"(" => 22,
			'NOT' => 60,
			"{" => 56,
			"\"" => 20,
			'REF' => 34,
			"\${" => 57
		},
		GOTOS => {
			'ident' => 77,
			'lterm' => 72,
			'item' => 40,
			'sterm' => 53,
			'term' => 55,
			'node' => 1,
			'expr' => 239
		}
	},
	{#State 155
		DEFAULT => 0
	},
	{#State 156
		ACTIONS => {
			"\$" => 33,
			'COMMA' => 106,
			'IDENT' => 15,
			'LITERAL' => 107,
			"\${" => 57
		},
		DEFAULT => -33,
		GOTOS => {
			'node' => 1,
			'ident' => 109,
			'assign' => 108,
			'item' => 40
		}
	},
	{#State 157
		ACTIONS => {
			"}" => 240
		}
	},
	{#State 158
		ACTIONS => {
			'COMMA' => 241,
			"\$" => 33,
			'LITERAL' => 160,
			"\${" => 57,
			'IDENT' => 15
		},
		DEFAULT => -119,
		GOTOS => {
			'param' => 242,
			'item' => 161
		}
	},
	{#State 159
		DEFAULT => -123
	},
	{#State 160
		ACTIONS => {
			'ASSIGN' => 243
		}
	},
	{#State 161
		ACTIONS => {
			'ASSIGN' => 244
		}
	},
	{#State 162
		ACTIONS => {
			"}" => 245
		}
	},
	{#State 163
		ACTIONS => {
			'CMPOP' => 129,
			"/" => 125,
			'MOD' => 131,
			'BINOP' => 132,
			'DIV' => 126,
			'CAT' => 127,
			"+" => 128
		},
		DEFAULT => -143
	},
	{#State 164
		DEFAULT => -37
	},
	{#State 165
		DEFAULT => -35
	},
	{#State 166
		DEFAULT => -43
	},
	{#State 167
		ACTIONS => {
			'IDENT' => 168,
			'COMMA' => 236
		},
		DEFAULT => -18,
		GOTOS => {
			'meta' => 237
		}
	},
	{#State 168
		ACTIONS => {
			'ASSIGN' => 235
		}
	},
	{#State 169
		ACTIONS => {
			";" => 246
		}
	},
	{#State 170
		DEFAULT => -4
	},
	{#State 171
		ACTIONS => {
			"\${" => 57,
			'LITERAL' => 107,
			'IDENT' => 15,
			'COMMA' => 106,
			"\$" => 33
		},
		DEFAULT => -32,
		GOTOS => {
			'node' => 1,
			'ident' => 109,
			'item' => 40,
			'assign' => 108
		}
	},
	{#State 172
		ACTIONS => {
			'BINOP' => 132,
			"?" => 124,
			'CMPOP' => 129,
			"/" => 125,
			'AND' => 133,
			'DIV' => 126,
			'OR' => 130,
			'CAT' => 127,
			'MOD' => 131,
			"+" => 128
		},
		DEFAULT => -31
	},
	{#State 173
		DEFAULT => -7
	},
	{#State 174
		DEFAULT => -61,
		GOTOS => {
			'@2-3' => 247
		}
	},
	{#State 175
		ACTIONS => {
			'LAST' => 41,
			'PROCESS' => 9,
			'TEXT' => 42,
			'FOR' => 43,
			'NUMBER' => 10,
			'perl' => 7,
			'RAW' => 39,
			'VIEW' => 36,
			'USE' => 37,
			'WHILE' => 2,
			'UNLESS' => 3,
			'REF' => 34,
			'GET' => 35,
			'STOP' => 5,
			'rawperl' => 18,
			'DEFAULT' => 54,
			'IDENT' => 15,
			'SWITCH' => 49,
			'LITERAL' => 50,
			'FILTER' => 16,
			'INSERT' => 12,
			'BLOCK' => 46,
			'WRAPPER' => 13,
			'RETURN' => 48,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'DEBUG' => 63,
			"[" => 26,
			'CLEAR' => 27,
			'META' => 65,
			'MACRO' => 21,
			'NOT' => 60,
			"(" => 22,
			'INCLUDE' => 62,
			'THROW' => 61,
			"\"" => 20,
			"{" => 56,
			"\${" => 57,
			";" => -19,
			'CALL' => 74,
			"\$" => 33,
			'SET' => 73,
			'NEXT' => 31,
			'IF' => 30
		},
		DEFAULT => -3,
		GOTOS => {
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'macro' => 38,
			'directive' => 6,
			'setlist' => 23,
			'chunk' => 59,
			'wrapper' => 8,
			'atomexpr' => 25,
			'block' => 248,
			'anonblock' => 24,
			'raw' => 66,
			'item' => 40,
			'ident' => 28,
			'filter' => 69,
			'capture' => 11,
			'chunks' => 68,
			'defblockname' => 67,
			'view' => 47,
			'defblock' => 29,
			'expr' => 32,
			'condition' => 71,
			'loop' => 17,
			'atomdir' => 14,
			'try' => 70,
			'term' => 55,
			'sterm' => 53,
			'use' => 19,
			'statement' => 75,
			'lterm' => 72,
			'assign' => 52
		}
	},
	{#State 176
		DEFAULT => -157,
		GOTOS => {
			'args' => 249
		}
	},
	{#State 177
		ACTIONS => {
			'NUMBER' => 84,
			"\"" => 89,
			'IDENT' => 83,
			'LITERAL' => 80,
			'FILENAME' => 90
		},
		GOTOS => {
			'name' => 250,
			'filename' => 87,
			'filepart' => 81
		}
	},
	{#State 178
		ACTIONS => {
			'IDENT' => 15,
			'LITERAL' => 253,
			"\$" => 33,
			'REF' => 34,
			"\"" => 20,
			"{" => 56,
			"\${" => 57,
			"(" => 22,
			'NOT' => 60,
			"[" => 26,
			'COMMA' => 252,
			'NUMBER' => 10
		},
		DEFAULT => -164,
		GOTOS => {
			'node' => 1,
			'param' => 251,
			'expr' => 255,
			'term' => 55,
			'sterm' => 53,
			'lterm' => 72,
			'item' => 254,
			'ident' => 256
		}
	},
	{#State 179
		ACTIONS => {
			'FILENAME' => 90,
			'IDENT' => 83,
			'NUMBER' => 84
		},
		GOTOS => {
			'filepart' => 257
		}
	},
	{#State 180
		ACTIONS => {
			'DOT' => 121
		},
		DEFAULT => -157,
		GOTOS => {
			'args' => 258
		}
	},
	{#State 181
		ACTIONS => {
			";" => 188,
			"\$" => 33,
			'TEXT' => 187,
			"\"" => 259,
			'IDENT' => 15,
			"\${" => 57
		},
		GOTOS => {
			'item' => 40,
			'ident' => 190,
			'node' => 1,
			'quotable' => 189
		}
	},
	{#State 182
		ACTIONS => {
			'RETURN' => 48,
			'BLOCK' => 46,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'DEFAULT' => 54,
			'rawperl' => 18,
			'LITERAL' => 50,
			'FILTER' => 16,
			'SWITCH' => 49,
			'IDENT' => 15,
			'USE' => 37,
			'VIEW' => 36,
			'STOP' => 5,
			'UNLESS' => 3,
			'REF' => 34,
			'WHILE' => 2,
			'GET' => 35,
			'FOR' => 43,
			'NUMBER' => 10,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'perl' => 7,
			'RAW' => 39,
			'IF' => 30,
			";" => -19,
			"\$" => 33,
			'SET' => 73,
			'CALL' => 74,
			'NEXT' => 31,
			'NOT' => 60,
			"(" => 22,
			'THROW' => 61,
			'INCLUDE' => 62,
			'MACRO' => 21,
			"\${" => 57,
			"{" => 56,
			"\"" => 20,
			"[" => 26,
			'CLEAR' => 27,
			'META' => 65,
			'DEBUG' => 63
		},
		DEFAULT => -3,
		GOTOS => {
			'use' => 19,
			'sterm' => 53,
			'term' => 55,
			'lterm' => 72,
			'assign' => 52,
			'statement' => 75,
			'expr' => 32,
			'loop' => 17,
			'condition' => 71,
			'atomdir' => 14,
			'try' => 70,
			'defblock' => 29,
			'view' => 47,
			'filter' => 69,
			'capture' => 11,
			'chunks' => 68,
			'defblockname' => 67,
			'ident' => 28,
			'item' => 40,
			'raw' => 66,
			'wrapper' => 8,
			'atomexpr' => 25,
			'anonblock' => 24,
			'block' => 260,
			'setlist' => 23,
			'directive' => 6,
			'macro' => 38,
			'chunk' => 59,
			'javascript' => 58,
			'switch' => 4,
			'node' => 1
		}
	},
	{#State 183
		ACTIONS => {
			'ASSIGN' => -133
		},
		DEFAULT => -131
	},
	{#State 184
		ACTIONS => {
			";" => 188,
			"\$" => 33,
			'TEXT' => 187,
			"\"" => 261,
			'IDENT' => 15,
			"\${" => 57
		},
		GOTOS => {
			'quotable' => 189,
			'node' => 1,
			'item' => 40,
			'ident' => 190
		}
	},
	{#State 185
		ACTIONS => {
			'NEXT' => 31,
			'CALL' => 74,
			"\$" => 33,
			'SET' => 73,
			";" => -19,
			'IF' => 30,
			'DEBUG' => 63,
			'META' => 65,
			'CLEAR' => 27,
			"[" => 26,
			"\"" => 20,
			"{" => 56,
			"\${" => 57,
			'MACRO' => 21,
			'THROW' => 61,
			'INCLUDE' => 62,
			"(" => 22,
			'NOT' => 60,
			'IDENT' => 15,
			'SWITCH' => 49,
			'FILTER' => 16,
			'LITERAL' => 50,
			'rawperl' => 18,
			'DEFAULT' => 54,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'BLOCK' => 46,
			'INSERT' => 12,
			'WRAPPER' => 13,
			'RETURN' => 48,
			'RAW' => 39,
			'perl' => 7,
			'PROCESS' => 9,
			'TEXT' => 42,
			'LAST' => 41,
			'NUMBER' => 10,
			'FOR' => 43,
			'GET' => 35,
			'UNLESS' => 3,
			'WHILE' => 2,
			'REF' => 34,
			'STOP' => 5,
			'VIEW' => 36,
			'USE' => 37
		},
		DEFAULT => -3,
		GOTOS => {
			'term' => 55,
			'sterm' => 53,
			'use' => 19,
			'statement' => 75,
			'assign' => 52,
			'lterm' => 72,
			'expr' => 32,
			'loop' => 17,
			'condition' => 71,
			'try' => 70,
			'atomdir' => 14,
			'view' => 47,
			'defblock' => 29,
			'filter' => 69,
			'capture' => 11,
			'defblockname' => 67,
			'chunks' => 68,
			'raw' => 66,
			'ident' => 28,
			'item' => 40,
			'wrapper' => 8,
			'atomexpr' => 25,
			'anonblock' => 24,
			'block' => 262,
			'macro' => 38,
			'setlist' => 23,
			'directive' => 6,
			'chunk' => 59,
			'javascript' => 58,
			'switch' => 4,
			'node' => 1
		}
	},
	{#State 186
		ACTIONS => {
			'LITERAL' => 80,
			'FILENAME' => 90,
			'IDENT' => 83,
			"\"" => 89,
			'NUMBER' => 84,
			"\$" => 88
		},
		GOTOS => {
			'nameargs' => 263,
			'filepart' => 81,
			'filename' => 87,
			'name' => 85,
			'names' => 86
		}
	},
	{#State 187
		DEFAULT => -179
	},
	{#State 188
		DEFAULT => -180
	},
	{#State 189
		DEFAULT => -176
	},
	{#State 190
		ACTIONS => {
			'DOT' => 121
		},
		DEFAULT => -178
	},
	{#State 191
		DEFAULT => -112
	},
	{#State 192
		DEFAULT => -93
	},
	{#State 193
		ACTIONS => {
			"/" => 125,
			'CMPOP' => 129,
			"?" => 124,
			'BINOP' => 132,
			'MOD' => 131,
			"+" => 128,
			'CAT' => 127,
			'OR' => 130,
			'DIV' => 126,
			'AND' => 133
		},
		DEFAULT => -28
	},
	{#State 194
		DEFAULT => -92
	},
	{#State 195
		ACTIONS => {
			"(" => 22,
			'NOT' => 60,
			"{" => 56,
			'REF' => 34,
			"\"" => 20,
			"\${" => 57,
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 264,
			'LITERAL' => 50,
			"[" => 26
		},
		GOTOS => {
			'sterm' => 53,
			'term' => 55,
			'assign' => 105,
			'lterm' => 72,
			'item' => 40,
			'ident' => 104,
			'expr' => 103,
			'margs' => 265,
			'node' => 1
		}
	},
	{#State 196
		ACTIONS => {
			";" => 266
		}
	},
	{#State 197
		DEFAULT => -146
	},
	{#State 198
		ACTIONS => {
			'REF' => 34,
			"{" => 56,
			"\"" => 20,
			"\${" => 57,
			'NOT' => 60,
			"(" => 22,
			'IDENT' => 15,
			'LITERAL' => 78,
			"[" => 26,
			"\$" => 33,
			'NUMBER' => 10
		},
		GOTOS => {
			'sterm' => 53,
			'term' => 55,
			'item' => 40,
			'lterm' => 72,
			'ident' => 77,
			'expr' => 267,
			'node' => 1
		}
	},
	{#State 199
		DEFAULT => -145
	},
	{#State 200
		DEFAULT => -68
	},
	{#State 201
		DEFAULT => -82
	},
	{#State 202
		ACTIONS => {
			'OR' => 130,
			'DIV' => 126,
			'BINOP' => 132,
			'AND' => 133,
			"/" => 125,
			'CMPOP' => 129,
			"?" => 124,
			'MOD' => 131,
			"+" => 128,
			'CAT' => 127
		},
		DEFAULT => -63
	},
	{#State 203
		ACTIONS => {
			'OR' => 130,
			'DIV' => 126,
			'AND' => 133,
			'BINOP' => 132,
			"/" => 125,
			'CMPOP' => 129,
			"+" => 128,
			'MOD' => 131,
			"?" => 124,
			'CAT' => 127
		},
		DEFAULT => -49
	},
	{#State 204
		ACTIONS => {
			'OR' => 130,
			'BINOP' => 132,
			'AND' => 133,
			'DIV' => 126,
			'CMPOP' => 129,
			"/" => 125,
			'CAT' => 127,
			'MOD' => 131,
			"?" => 124,
			"+" => 128
		},
		DEFAULT => -47
	},
	{#State 205
		DEFAULT => -60
	},
	{#State 206
		DEFAULT => -107
	},
	{#State 207
		DEFAULT => -115
	},
	{#State 208
		DEFAULT => -106
	},
	{#State 209
		DEFAULT => -116
	},
	{#State 210
		ACTIONS => {
			'NUMBER' => 10,
			"\$" => 33,
			'LITERAL' => 78,
			"\${" => 57,
			"\"" => 20,
			'REF' => 34,
			'IDENT' => 15
		},
		GOTOS => {
			'ident' => 77,
			'item' => 40,
			'sterm' => 268,
			'node' => 1
		}
	},
	{#State 211
		DEFAULT => -126
	},
	{#State 212
		DEFAULT => -127
	},
	{#State 213
		DEFAULT => -90
	},
	{#State 214
		ACTIONS => {
			'CAT' => 127,
			'MOD' => 131,
			"+" => 128,
			'AND' => 133,
			";" => -151,
			"\$" => -151,
			'DIV' => 126,
			'LITERAL' => -151,
			'IDENT' => -151,
			'OR' => 130,
			"?" => 124,
			'CMPOP' => 129,
			"\${" => -151,
			"/" => 125,
			'BINOP' => 132,
			'COMMA' => -151
		},
		DEFAULT => -28
	},
	{#State 215
		ACTIONS => {
			'DEFAULT' => 54,
			'rawperl' => 18,
			'LITERAL' => 50,
			'FILTER' => 16,
			'SWITCH' => 49,
			'IDENT' => 15,
			'RETURN' => 48,
			'INSERT' => 12,
			'WRAPPER' => 13,
			'BLOCK' => 46,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'FOR' => 43,
			'NUMBER' => 10,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'perl' => 7,
			'RAW' => 39,
			'VIEW' => 36,
			'USE' => 37,
			'STOP' => 5,
			'WHILE' => 2,
			'REF' => 34,
			'UNLESS' => 3,
			'GET' => 35,
			";" => -19,
			'SET' => 73,
			"\$" => 33,
			'CALL' => 74,
			'NEXT' => 31,
			'IF' => 30,
			"[" => 26,
			'CLEAR' => 27,
			'META' => 65,
			'DEBUG' => 63,
			'NOT' => 60,
			"(" => 22,
			'INCLUDE' => 62,
			'THROW' => 61,
			'MACRO' => 21,
			"\${" => 57,
			"{" => 56,
			"\"" => 20
		},
		DEFAULT => -3,
		GOTOS => {
			'atomexpr' => 25,
			'anonblock' => 24,
			'block' => 269,
			'wrapper' => 8,
			'ident' => 28,
			'item' => 40,
			'raw' => 66,
			'switch' => 4,
			'node' => 1,
			'javascript' => 58,
			'chunk' => 59,
			'setlist' => 23,
			'directive' => 6,
			'macro' => 38,
			'atomdir' => 14,
			'try' => 70,
			'condition' => 71,
			'expr' => 32,
			'loop' => 17,
			'lterm' => 72,
			'assign' => 52,
			'statement' => 75,
			'sterm' => 53,
			'use' => 19,
			'term' => 55,
			'chunks' => 68,
			'capture' => 11,
			'defblockname' => 67,
			'filter' => 69,
			'defblock' => 29,
			'view' => 47
		}
	},
	{#State 216
		ACTIONS => {
			'OR' => 130,
			'AND' => 133,
			":" => 270,
			'BINOP' => 132,
			'DIV' => 126,
			'CMPOP' => 129,
			"/" => 125,
			'CAT' => 127,
			"+" => 128,
			'MOD' => 131,
			"?" => 124
		}
	},
	{#State 217
		ACTIONS => {
			'MOD' => 131,
			'DIV' => 126
		},
		DEFAULT => -135
	},
	{#State 218
		ACTIONS => {
			'MOD' => 131
		},
		DEFAULT => -137
	},
	{#State 219
		ACTIONS => {
			'BINOP' => 132,
			"+" => 128,
			'DIV' => 126,
			"/" => 125,
			'CMPOP' => 129,
			'MOD' => 131
		},
		DEFAULT => -140
	},
	{#State 220
		ACTIONS => {
			'DIV' => 126,
			"/" => 125,
			'MOD' => 131
		},
		DEFAULT => -136
	},
	{#State 221
		ACTIONS => {
			"/" => 125,
			'MOD' => 131,
			'BINOP' => 132,
			"+" => 128,
			'DIV' => 126
		},
		DEFAULT => -139
	},
	{#State 222
		ACTIONS => {
			"/" => 125,
			'CMPOP' => 129,
			'MOD' => 131,
			'BINOP' => 132,
			'DIV' => 126,
			"+" => 128,
			'CAT' => 127
		},
		DEFAULT => -142
	},
	{#State 223
		DEFAULT => -138
	},
	{#State 224
		ACTIONS => {
			"/" => 125,
			'MOD' => 131,
			"+" => 128,
			'DIV' => 126
		},
		DEFAULT => -134
	},
	{#State 225
		ACTIONS => {
			'DIV' => 126,
			'CAT' => 127,
			"+" => 128,
			'BINOP' => 132,
			'MOD' => 131,
			'CMPOP' => 129,
			"/" => 125
		},
		DEFAULT => -141
	},
	{#State 226
		DEFAULT => -77,
		GOTOS => {
			'@3-3' => 271
		}
	},
	{#State 227
		ACTIONS => {
			'LITERAL' => 253,
			"[" => 26,
			")" => 272,
			'IDENT' => 15,
			'COMMA' => 252,
			'NUMBER' => 10,
			"\$" => 33,
			"\${" => 57,
			"\"" => 20,
			'REF' => 34,
			"{" => 56,
			'NOT' => 60,
			"(" => 22
		},
		GOTOS => {
			'expr' => 255,
			'item' => 254,
			'ident' => 256,
			'lterm' => 72,
			'term' => 55,
			'sterm' => 53,
			'node' => 1,
			'param' => 251
		}
	},
	{#State 228
		ACTIONS => {
			"\${" => 57,
			"\"" => 20,
			"{" => 56,
			'REF' => 34,
			'NUMBER' => 10,
			"\$" => 33,
			"[" => 26,
			'LITERAL' => 78,
			'IDENT' => 15
		},
		GOTOS => {
			'node' => 1,
			'sterm' => 53,
			'term' => 273,
			'lterm' => 72,
			'ident' => 77,
			'item' => 40
		}
	},
	{#State 229
		ACTIONS => {
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			'LITERAL' => 78,
			"[" => 26,
			"{" => 56,
			"\"" => 20,
			'REF' => 34,
			"\${" => 57
		},
		GOTOS => {
			'sterm' => 53,
			'term' => 274,
			'ident' => 77,
			'item' => 40,
			'lterm' => 72,
			'node' => 1
		}
	},
	{#State 230
		ACTIONS => {
			'LITERAL' => 253,
			"[" => 26,
			'IDENT' => 15,
			'NUMBER' => 10,
			'COMMA' => 252,
			"\$" => 33,
			"\${" => 57,
			"{" => 56,
			"\"" => 20,
			'REF' => 34,
			'NOT' => 60,
			"(" => 22
		},
		DEFAULT => -66,
		GOTOS => {
			'node' => 1,
			'param' => 251,
			'expr' => 255,
			'sterm' => 53,
			'term' => 55,
			'lterm' => 72,
			'item' => 254,
			'ident' => 256
		}
	},
	{#State 231
		DEFAULT => -58,
		GOTOS => {
			'@1-3' => 275
		}
	},
	{#State 232
		ACTIONS => {
			'CATCH' => 278,
			'FINAL' => 277
		},
		DEFAULT => -74,
		GOTOS => {
			'final' => 276
		}
	},
	{#State 233
		ACTIONS => {
			'THROW' => 61,
			'INCLUDE' => 62,
			'NOT' => 60,
			"(" => 22,
			'MACRO' => 21,
			"\${" => 57,
			"{" => 56,
			"\"" => 20,
			'META' => 65,
			'CLEAR' => 27,
			"[" => 26,
			'DEBUG' => 63,
			'IF' => 30,
			"\$" => 33,
			'CALL' => 74,
			'SET' => 73,
			";" => -19,
			'NEXT' => 31,
			'VIEW' => 36,
			'USE' => 37,
			'STOP' => 5,
			'GET' => 35,
			'REF' => 34,
			'UNLESS' => 3,
			'WHILE' => 2,
			'NUMBER' => 10,
			'FOR' => 43,
			'PROCESS' => 9,
			'TEXT' => 42,
			'LAST' => 41,
			'RAW' => 39,
			'perl' => 7,
			'RETURN' => 48,
			'WRAPPER' => 13,
			'BLOCK' => 46,
			'INSERT' => 12,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'DEFAULT' => 54,
			'rawperl' => 18,
			'LITERAL' => 50,
			'FILTER' => 16,
			'SWITCH' => 49,
			'IDENT' => 15
		},
		DEFAULT => -3,
		GOTOS => {
			'wrapper' => 8,
			'atomexpr' => 25,
			'block' => 279,
			'anonblock' => 24,
			'item' => 40,
			'ident' => 28,
			'raw' => 66,
			'javascript' => 58,
			'node' => 1,
			'switch' => 4,
			'setlist' => 23,
			'directive' => 6,
			'macro' => 38,
			'chunk' => 59,
			'condition' => 71,
			'loop' => 17,
			'expr' => 32,
			'atomdir' => 14,
			'try' => 70,
			'sterm' => 53,
			'use' => 19,
			'term' => 55,
			'assign' => 52,
			'lterm' => 72,
			'statement' => 75,
			'filter' => 69,
			'capture' => 11,
			'chunks' => 68,
			'defblockname' => 67,
			'defblock' => 29,
			'view' => 47
		}
	},
	{#State 234
		ACTIONS => {
			'DEFAULT' => 54,
			'rawperl' => 18,
			'FILTER' => 16,
			'LITERAL' => 50,
			'IDENT' => 15,
			'SWITCH' => 49,
			'RETURN' => 48,
			'BLOCK' => 46,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'NUMBER' => 10,
			'FOR' => 43,
			'TEXT' => 42,
			'PROCESS' => 9,
			'LAST' => 41,
			'RAW' => 39,
			'perl' => 7,
			'VIEW' => 36,
			'USE' => 37,
			'STOP' => 5,
			'GET' => 35,
			'UNLESS' => 3,
			'WHILE' => 2,
			'REF' => 34,
			'SET' => 73,
			"\$" => 33,
			'CALL' => 74,
			";" => -19,
			'NEXT' => 31,
			'IF' => 30,
			'CLEAR' => 27,
			'META' => 65,
			"[" => 26,
			'DEBUG' => 63,
			'INCLUDE' => 62,
			'THROW' => 61,
			"(" => 22,
			'NOT' => 60,
			'MACRO' => 21,
			"\${" => 57,
			"\"" => 20,
			"{" => 56
		},
		DEFAULT => -3,
		GOTOS => {
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'setlist' => 23,
			'directive' => 6,
			'macro' => 38,
			'chunk' => 59,
			'wrapper' => 8,
			'block' => 280,
			'atomexpr' => 25,
			'anonblock' => 24,
			'item' => 40,
			'ident' => 28,
			'raw' => 66,
			'filter' => 69,
			'capture' => 11,
			'defblockname' => 67,
			'chunks' => 68,
			'defblock' => 29,
			'view' => 47,
			'loop' => 17,
			'expr' => 32,
			'condition' => 71,
			'atomdir' => 14,
			'try' => 70,
			'sterm' => 53,
			'use' => 19,
			'term' => 55,
			'lterm' => 72,
			'assign' => 52,
			'statement' => 75
		}
	},
	{#State 235
		ACTIONS => {
			"\"" => 282,
			'LITERAL' => 281,
			'NUMBER' => 283
		}
	},
	{#State 236
		DEFAULT => -99
	},
	{#State 237
		DEFAULT => -98
	},
	{#State 238
		ACTIONS => {
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'RETURN' => 48,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'BLOCK' => 46,
			'FILTER' => 16,
			'LITERAL' => 50,
			'IDENT' => 15,
			'SWITCH' => 49,
			'DEFAULT' => 54,
			'rawperl' => 18,
			'STOP' => 5,
			'GET' => 35,
			'UNLESS' => 3,
			'REF' => 34,
			'WHILE' => 2,
			'USE' => 37,
			'VIEW' => 36,
			'RAW' => 39,
			'perl' => 7,
			'NUMBER' => 10,
			'FOR' => 43,
			'TEXT' => 42,
			'PROCESS' => 9,
			'LAST' => 41,
			'IF' => 30,
			'NEXT' => 31,
			"\$" => 33,
			'SET' => 73,
			'CALL' => 74,
			";" => -19,
			"\${" => 57,
			"{" => 56,
			"\"" => 20,
			'THROW' => 61,
			'INCLUDE' => 62,
			"(" => 22,
			'NOT' => 60,
			'MACRO' => 21,
			'META' => 65,
			'CLEAR' => 27,
			"[" => 26,
			'DEBUG' => 63
		},
		DEFAULT => -3,
		GOTOS => {
			'filter' => 69,
			'chunks' => 68,
			'capture' => 11,
			'defblockname' => 67,
			'view' => 47,
			'defblock' => 29,
			'loop' => 17,
			'expr' => 32,
			'condition' => 71,
			'try' => 70,
			'atomdir' => 14,
			'term' => 55,
			'use' => 19,
			'sterm' => 53,
			'statement' => 75,
			'lterm' => 72,
			'assign' => 52,
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'macro' => 38,
			'directive' => 6,
			'setlist' => 23,
			'chunk' => 59,
			'wrapper' => 8,
			'atomexpr' => 25,
			'block' => 284,
			'anonblock' => 24,
			'raw' => 66,
			'ident' => 28,
			'item' => 40
		}
	},
	{#State 239
		ACTIONS => {
			'CMPOP' => 129,
			"/" => 125,
			"?" => 124,
			'BINOP' => 132,
			'CAT' => 127,
			"+" => 128,
			'MOD' => 131,
			'OR' => 130,
			'AND' => 133,
			'DIV' => 126
		},
		DEFAULT => -152
	},
	{#State 240
		DEFAULT => -109
	},
	{#State 241
		DEFAULT => -122
	},
	{#State 242
		DEFAULT => -121
	},
	{#State 243
		ACTIONS => {
			"{" => 56,
			'REF' => 34,
			"\"" => 20,
			"\${" => 57,
			"(" => 22,
			'NOT' => 60,
			'IDENT' => 15,
			'LITERAL' => 78,
			"[" => 26,
			"\$" => 33,
			'NUMBER' => 10
		},
		GOTOS => {
			'node' => 1,
			'expr' => 285,
			'lterm' => 72,
			'item' => 40,
			'ident' => 77,
			'term' => 55,
			'sterm' => 53
		}
	},
	{#State 244
		ACTIONS => {
			'REF' => 34,
			"\"" => 20,
			"{" => 56,
			"\${" => 57,
			"(" => 22,
			'NOT' => 60,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78,
			"\$" => 33,
			'NUMBER' => 10
		},
		GOTOS => {
			'item' => 40,
			'ident' => 77,
			'lterm' => 72,
			'sterm' => 53,
			'term' => 55,
			'node' => 1,
			'expr' => 286
		}
	},
	{#State 245
		DEFAULT => -132
	},
	{#State 246
		ACTIONS => {
			'NUMBER' => 10,
			'FOR' => 43,
			'TEXT' => 42,
			'PROCESS' => 9,
			'LAST' => 41,
			'RAW' => 39,
			'perl' => 7,
			'USE' => 37,
			'VIEW' => 36,
			'STOP' => 5,
			'GET' => 35,
			'REF' => 34,
			'UNLESS' => 3,
			'WHILE' => 2,
			'DEFAULT' => 54,
			'rawperl' => 18,
			'LITERAL' => 50,
			'FILTER' => 16,
			'SWITCH' => 49,
			'IDENT' => 15,
			'RETURN' => 48,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'BLOCK' => 46,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'CLEAR' => 27,
			'META' => 65,
			"[" => 26,
			'DEBUG' => 63,
			'THROW' => 61,
			'INCLUDE' => 62,
			"(" => 22,
			'NOT' => 60,
			'MACRO' => 21,
			"\${" => 57,
			"{" => 56,
			"\"" => 20,
			"\$" => 33,
			'CALL' => 74,
			'SET' => 73,
			";" => -19,
			'NEXT' => 31,
			'IF' => 30
		},
		DEFAULT => -3,
		GOTOS => {
			'statement' => 75,
			'lterm' => 72,
			'try' => 70,
			'condition' => 71,
			'expr' => 32,
			'defblock' => 29,
			'defblockname' => 67,
			'chunks' => 68,
			'filter' => 69,
			'raw' => 66,
			'ident' => 28,
			'block' => 64,
			'anonblock' => 24,
			'atomexpr' => 25,
			'chunk' => 59,
			'setlist' => 23,
			'javascript' => 58,
			'assign' => 52,
			'term' => 55,
			'sterm' => 53,
			'use' => 19,
			'atomdir' => 14,
			'template' => 287,
			'loop' => 17,
			'view' => 47,
			'capture' => 11,
			'item' => 40,
			'wrapper' => 8,
			'macro' => 38,
			'directive' => 6,
			'switch' => 4,
			'node' => 1
		}
	},
	{#State 247
		ACTIONS => {
			'DEBUG' => 63,
			"[" => 26,
			'META' => 65,
			'CLEAR' => 27,
			'MACRO' => 21,
			'NOT' => 60,
			"(" => 22,
			'INCLUDE' => 62,
			'THROW' => 61,
			"{" => 56,
			"\"" => 20,
			"\${" => 57,
			";" => -19,
			'CALL' => 74,
			'SET' => 73,
			"\$" => 33,
			'NEXT' => 31,
			'IF' => 30,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'FOR' => 43,
			'NUMBER' => 10,
			'perl' => 7,
			'RAW' => 39,
			'VIEW' => 36,
			'USE' => 37,
			'REF' => 34,
			'UNLESS' => 3,
			'WHILE' => 2,
			'GET' => 35,
			'STOP' => 5,
			'rawperl' => 18,
			'DEFAULT' => 54,
			'IDENT' => 15,
			'SWITCH' => 49,
			'FILTER' => 16,
			'LITERAL' => 50,
			'BLOCK' => 46,
			'INSERT' => 12,
			'WRAPPER' => 13,
			'RETURN' => 48,
			'TRY' => 44,
			'JAVASCRIPT' => 45
		},
		DEFAULT => -3,
		GOTOS => {
			'raw' => 66,
			'item' => 40,
			'ident' => 28,
			'anonblock' => 24,
			'block' => 288,
			'atomexpr' => 25,
			'wrapper' => 8,
			'chunk' => 59,
			'macro' => 38,
			'setlist' => 23,
			'directive' => 6,
			'node' => 1,
			'switch' => 4,
			'javascript' => 58,
			'statement' => 75,
			'assign' => 52,
			'lterm' => 72,
			'term' => 55,
			'sterm' => 53,
			'use' => 19,
			'try' => 70,
			'atomdir' => 14,
			'condition' => 71,
			'loop' => 17,
			'expr' => 32,
			'view' => 47,
			'defblock' => 29,
			'chunks' => 68,
			'defblockname' => 67,
			'capture' => 11,
			'filter' => 69
		}
	},
	{#State 248
		ACTIONS => {
			'ELSIF' => 289,
			'ELSE' => 290
		},
		DEFAULT => -52,
		GOTOS => {
			'else' => 291
		}
	},
	{#State 249
		ACTIONS => {
			"\${" => 57,
			"{" => 56,
			'REF' => 34,
			"\"" => 20,
			"(" => 22,
			'NOT' => 60,
			"[" => 26,
			'LITERAL' => 253,
			'IDENT' => 15,
			")" => 292,
			'COMMA' => 252,
			'NUMBER' => 10,
			"\$" => 33
		},
		GOTOS => {
			'param' => 251,
			'node' => 1,
			'term' => 55,
			'sterm' => 53,
			'ident' => 256,
			'item' => 254,
			'lterm' => 72,
			'expr' => 255
		}
	},
	{#State 250
		DEFAULT => -166
	},
	{#State 251
		DEFAULT => -154
	},
	{#State 252
		DEFAULT => -156
	},
	{#State 253
		ACTIONS => {
			'ASSIGN' => 243
		},
		DEFAULT => -113
	},
	{#State 254
		ACTIONS => {
			"(" => 140,
			'ASSIGN' => 244
		},
		DEFAULT => -129
	},
	{#State 255
		ACTIONS => {
			'CAT' => 127,
			'MOD' => 131,
			"+" => 128,
			'AND' => 133,
			'DIV' => 126,
			'OR' => 130,
			"?" => 124,
			'CMPOP' => 129,
			"/" => 125,
			'BINOP' => 132
		},
		DEFAULT => -153
	},
	{#State 256
		ACTIONS => {
			'ASSIGN' => 293,
			'DOT' => 121
		},
		DEFAULT => -110
	},
	{#State 257
		DEFAULT => -171
	},
	{#State 258
		ACTIONS => {
			"[" => 26,
			'NUMBER' => 10,
			'COMMA' => 252,
			"\"" => 20,
			"{" => 56,
			'REF' => 34,
			"\${" => 57,
			"(" => 22,
			'NOT' => 60,
			'IDENT' => 15,
			'LITERAL' => 253,
			"\$" => 33
		},
		DEFAULT => -163,
		GOTOS => {
			'term' => 55,
			'sterm' => 53,
			'item' => 254,
			'lterm' => 72,
			'ident' => 256,
			'expr' => 255,
			'param' => 251,
			'node' => 1
		}
	},
	{#State 259
		DEFAULT => -168
	},
	{#State 260
		ACTIONS => {
			'END' => 294
		}
	},
	{#State 261
		ACTIONS => {
			'ASSIGN' => -161
		},
		DEFAULT => -168
	},
	{#State 262
		ACTIONS => {
			'END' => 295
		}
	},
	{#State 263
		DEFAULT => -158
	},
	{#State 264
		ACTIONS => {
			'IDENT' => -97,
			")" => -97,
			'COMMA' => -97
		},
		DEFAULT => -131
	},
	{#State 265
		ACTIONS => {
			'COMMA' => 298,
			")" => 297,
			'IDENT' => 296
		}
	},
	{#State 266
		ACTIONS => {
			'RAW' => 39,
			'perl' => 7,
			'PROCESS' => 9,
			'TEXT' => 42,
			'LAST' => 41,
			'NUMBER' => 10,
			'FOR' => 43,
			'GET' => 35,
			'UNLESS' => 3,
			'WHILE' => 2,
			'REF' => 34,
			'STOP' => 5,
			'VIEW' => 36,
			'USE' => 37,
			'IDENT' => 15,
			'SWITCH' => 49,
			'LITERAL' => 50,
			'FILTER' => 16,
			'rawperl' => 18,
			'DEFAULT' => 54,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'BLOCK' => 46,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'RETURN' => 48,
			'DEBUG' => 63,
			'CLEAR' => 27,
			'META' => 65,
			"[" => 26,
			"\"" => 20,
			"{" => 56,
			"\${" => 57,
			'MACRO' => 21,
			'THROW' => 61,
			'INCLUDE' => 62,
			"(" => 22,
			'NOT' => 60,
			'NEXT' => 31,
			"\$" => 33,
			'CALL' => 74,
			'SET' => 73,
			";" => -19,
			'IF' => 30
		},
		DEFAULT => -3,
		GOTOS => {
			'wrapper' => 8,
			'atomexpr' => 25,
			'anonblock' => 24,
			'block' => 299,
			'item' => 40,
			'ident' => 28,
			'raw' => 66,
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'setlist' => 23,
			'directive' => 6,
			'macro' => 38,
			'chunk' => 59,
			'loop' => 17,
			'condition' => 71,
			'expr' => 32,
			'atomdir' => 14,
			'try' => 70,
			'use' => 19,
			'sterm' => 53,
			'term' => 55,
			'assign' => 52,
			'lterm' => 72,
			'statement' => 75,
			'filter' => 69,
			'chunks' => 68,
			'capture' => 11,
			'defblockname' => 67,
			'defblock' => 29,
			'view' => 47
		}
	},
	{#State 267
		ACTIONS => {
			'DIV' => 126,
			'AND' => 133,
			'OR' => 130,
			"+" => 128,
			'MOD' => 131,
			'CAT' => 127,
			'BINOP' => 132,
			"?" => 124,
			"/" => 125,
			'CMPOP' => 129
		},
		DEFAULT => -151
	},
	{#State 268
		DEFAULT => -118
	},
	{#State 269
		ACTIONS => {
			'ELSIF' => 289,
			'ELSE' => 290
		},
		DEFAULT => -52,
		GOTOS => {
			'else' => 300
		}
	},
	{#State 270
		ACTIONS => {
			'NOT' => 60,
			"(" => 22,
			'REF' => 34,
			"{" => 56,
			"\"" => 20,
			"\${" => 57,
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78
		},
		GOTOS => {
			'item' => 40,
			'ident' => 77,
			'lterm' => 72,
			'term' => 55,
			'sterm' => 53,
			'node' => 1,
			'expr' => 301
		}
	},
	{#State 271
		ACTIONS => {
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'BLOCK' => 46,
			'INSERT' => 12,
			'WRAPPER' => 13,
			'RETURN' => 48,
			'IDENT' => 15,
			'SWITCH' => 49,
			'LITERAL' => 50,
			'FILTER' => 16,
			'rawperl' => 18,
			'DEFAULT' => 54,
			'UNLESS' => 3,
			'WHILE' => 2,
			'REF' => 34,
			'GET' => 35,
			'STOP' => 5,
			'VIEW' => 36,
			'USE' => 37,
			'perl' => 7,
			'RAW' => 39,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'FOR' => 43,
			'NUMBER' => 10,
			'IF' => 30,
			'NEXT' => 31,
			";" => -19,
			'CALL' => 74,
			'SET' => 73,
			"\$" => 33,
			"{" => 56,
			"\"" => 20,
			"\${" => 57,
			'MACRO' => 21,
			'NOT' => 60,
			"(" => 22,
			'THROW' => 61,
			'INCLUDE' => 62,
			'DEBUG' => 63,
			"[" => 26,
			'META' => 65,
			'CLEAR' => 27
		},
		DEFAULT => -3,
		GOTOS => {
			'chunks' => 68,
			'capture' => 11,
			'defblockname' => 67,
			'filter' => 69,
			'defblock' => 29,
			'view' => 47,
			'atomdir' => 14,
			'try' => 70,
			'condition' => 71,
			'expr' => 32,
			'loop' => 17,
			'assign' => 52,
			'lterm' => 72,
			'statement' => 75,
			'sterm' => 53,
			'use' => 19,
			'term' => 55,
			'node' => 1,
			'switch' => 4,
			'javascript' => 58,
			'chunk' => 59,
			'setlist' => 23,
			'directive' => 6,
			'macro' => 38,
			'anonblock' => 24,
			'block' => 302,
			'atomexpr' => 25,
			'wrapper' => 8,
			'ident' => 28,
			'item' => 40,
			'raw' => 66
		}
	},
	{#State 272
		DEFAULT => -130
	},
	{#State 273
		DEFAULT => -157,
		GOTOS => {
			'args' => 303
		}
	},
	{#State 274
		DEFAULT => -157,
		GOTOS => {
			'args' => 304
		}
	},
	{#State 275
		ACTIONS => {
			'PROCESS' => 9,
			'TEXT' => 42,
			'LAST' => 41,
			'NUMBER' => 10,
			'FOR' => 43,
			'RAW' => 39,
			'perl' => 7,
			'USE' => 37,
			'VIEW' => 36,
			'GET' => 35,
			'UNLESS' => 3,
			'WHILE' => 2,
			'REF' => 34,
			'STOP' => 5,
			'rawperl' => 18,
			'DEFAULT' => 54,
			'IDENT' => 15,
			'SWITCH' => 49,
			'FILTER' => 16,
			'LITERAL' => 50,
			'BLOCK' => 46,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'RETURN' => 48,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'DEBUG' => 63,
			'CLEAR' => 27,
			'META' => 65,
			"[" => 26,
			'MACRO' => 21,
			'THROW' => 61,
			'INCLUDE' => 62,
			"(" => 22,
			'NOT' => 60,
			"\"" => 20,
			"{" => 56,
			"\${" => 57,
			"\$" => 33,
			'SET' => 73,
			'CALL' => 74,
			";" => -19,
			'NEXT' => 31,
			'IF' => 30
		},
		DEFAULT => -3,
		GOTOS => {
			'item' => 40,
			'ident' => 28,
			'raw' => 66,
			'anonblock' => 24,
			'atomexpr' => 25,
			'block' => 305,
			'wrapper' => 8,
			'chunk' => 59,
			'setlist' => 23,
			'directive' => 6,
			'macro' => 38,
			'node' => 1,
			'switch' => 4,
			'javascript' => 58,
			'lterm' => 72,
			'assign' => 52,
			'statement' => 75,
			'use' => 19,
			'sterm' => 53,
			'term' => 55,
			'atomdir' => 14,
			'try' => 70,
			'condition' => 71,
			'loop' => 17,
			'expr' => 32,
			'defblock' => 29,
			'view' => 47,
			'capture' => 11,
			'defblockname' => 67,
			'chunks' => 68,
			'filter' => 69
		}
	},
	{#State 276
		ACTIONS => {
			'END' => 306
		}
	},
	{#State 277
		ACTIONS => {
			";" => 307
		}
	},
	{#State 278
		ACTIONS => {
			'DEFAULT' => 310,
			'NUMBER' => 84,
			";" => 309,
			'FILENAME' => 90,
			'IDENT' => 83
		},
		GOTOS => {
			'filepart' => 81,
			'filename' => 308
		}
	},
	{#State 279
		ACTIONS => {
			'END' => 311
		}
	},
	{#State 280
		ACTIONS => {
			'END' => 312
		}
	},
	{#State 281
		DEFAULT => -101
	},
	{#State 282
		ACTIONS => {
			'TEXT' => 313
		}
	},
	{#State 283
		DEFAULT => -103
	},
	{#State 284
		ACTIONS => {
			'CASE' => 315
		},
		DEFAULT => -57,
		GOTOS => {
			'case' => 314
		}
	},
	{#State 285
		ACTIONS => {
			'CMPOP' => 129,
			"/" => 125,
			"?" => 124,
			'OR' => 130,
			'MOD' => 131,
			'BINOP' => 132,
			'AND' => 133,
			'DIV' => 126,
			'CAT' => 127,
			"+" => 128
		},
		DEFAULT => -124
	},
	{#State 286
		ACTIONS => {
			'CMPOP' => 129,
			"/" => 125,
			"?" => 124,
			'MOD' => 131,
			'OR' => 130,
			'BINOP' => 132,
			'CAT' => 127,
			"+" => 128,
			'AND' => 133,
			'DIV' => 126
		},
		DEFAULT => -125
	},
	{#State 287
		ACTIONS => {
			'END' => 316
		}
	},
	{#State 288
		ACTIONS => {
			'END' => 317
		}
	},
	{#State 289
		ACTIONS => {
			"\$" => 33,
			'NUMBER' => 10,
			'IDENT' => 15,
			"[" => 26,
			'LITERAL' => 78,
			"(" => 22,
			'NOT' => 60,
			"\"" => 20,
			'REF' => 34,
			"{" => 56,
			"\${" => 57
		},
		GOTOS => {
			'sterm' => 53,
			'term' => 55,
			'item' => 40,
			'lterm' => 72,
			'ident' => 77,
			'expr' => 318,
			'node' => 1
		}
	},
	{#State 290
		ACTIONS => {
			";" => 319
		}
	},
	{#State 291
		ACTIONS => {
			'END' => 320
		}
	},
	{#State 292
		DEFAULT => -165
	},
	{#State 293
		ACTIONS => {
			"[" => 26,
			'LITERAL' => 78,
			'IDENT' => 15,
			'NUMBER' => 10,
			"\$" => 33,
			"\${" => 57,
			"\"" => 20,
			"{" => 56,
			'REF' => 34,
			'NOT' => 60,
			"(" => 22
		},
		GOTOS => {
			'expr' => 321,
			'node' => 1,
			'term' => 55,
			'sterm' => 53,
			'item' => 40,
			'ident' => 77,
			'lterm' => 72
		}
	},
	{#State 294
		DEFAULT => -67
	},
	{#State 295
		DEFAULT => -81
	},
	{#State 296
		DEFAULT => -95
	},
	{#State 297
		ACTIONS => {
			'LITERAL' => 50,
			'FILTER' => 16,
			'SWITCH' => 49,
			'IDENT' => 15,
			'DEFAULT' => 54,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'RETURN' => 48,
			'WRAPPER' => 13,
			'BLOCK' => 196,
			'INSERT' => 12,
			'perl' => 7,
			'NUMBER' => 10,
			'FOR' => 43,
			'PROCESS' => 9,
			'LAST' => 41,
			'STOP' => 5,
			'GET' => 35,
			'UNLESS' => 3,
			'REF' => 34,
			'WHILE' => 2,
			'NEXT' => 31,
			"\$" => 33,
			'SET' => 73,
			'CALL' => 74,
			'IF' => 30,
			'CLEAR' => 27,
			"[" => 26,
			'DEBUG' => 63,
			"\${" => 57,
			"\"" => 20,
			"{" => 56,
			'THROW' => 61,
			'INCLUDE' => 62,
			"(" => 22,
			'NOT' => 60
		},
		GOTOS => {
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'directive' => 192,
			'setlist' => 23,
			'wrapper' => 8,
			'atomexpr' => 25,
			'ident' => 104,
			'item' => 40,
			'filter' => 69,
			'mdir' => 322,
			'expr' => 193,
			'condition' => 71,
			'loop' => 17,
			'atomdir' => 14,
			'try' => 70,
			'term' => 55,
			'sterm' => 53,
			'assign' => 52,
			'lterm' => 72
		}
	},
	{#State 298
		DEFAULT => -96
	},
	{#State 299
		ACTIONS => {
			'END' => 323
		}
	},
	{#State 300
		ACTIONS => {
			'END' => 324
		}
	},
	{#State 301
		ACTIONS => {
			"+" => 128,
			'CAT' => 127,
			'DIV' => 126,
			'AND' => 133,
			'BINOP' => 132,
			'MOD' => 131,
			'OR' => 130,
			"?" => 124,
			"/" => 125,
			'CMPOP' => 129
		},
		DEFAULT => -144
	},
	{#State 302
		ACTIONS => {
			'END' => 325
		}
	},
	{#State 303
		ACTIONS => {
			'COMMA' => 252,
			'NUMBER' => 10,
			"\$" => 33,
			'LITERAL' => 253,
			"[" => 26,
			'IDENT' => 15,
			'NOT' => 60,
			"(" => 22,
			"\${" => 57,
			'REF' => 34,
			"{" => 56,
			"\"" => 20
		},
		DEFAULT => -65,
		GOTOS => {
			'expr' => 255,
			'lterm' => 72,
			'ident' => 256,
			'item' => 254,
			'term' => 55,
			'sterm' => 53,
			'node' => 1,
			'param' => 251
		}
	},
	{#State 304
		ACTIONS => {
			"(" => 22,
			'NOT' => 60,
			"{" => 56,
			"\"" => 20,
			'REF' => 34,
			"\${" => 57,
			"\$" => 33,
			'NUMBER' => 10,
			'COMMA' => 252,
			'IDENT' => 15,
			'LITERAL' => 253,
			"[" => 26
		},
		DEFAULT => -64,
		GOTOS => {
			'expr' => 255,
			'sterm' => 53,
			'term' => 55,
			'ident' => 256,
			'item' => 254,
			'lterm' => 72,
			'node' => 1,
			'param' => 251
		}
	},
	{#State 305
		ACTIONS => {
			'END' => 326
		}
	},
	{#State 306
		DEFAULT => -69
	},
	{#State 307
		ACTIONS => {
			'IF' => 30,
			'CALL' => 74,
			"\$" => 33,
			'SET' => 73,
			";" => -19,
			'NEXT' => 31,
			'THROW' => 61,
			'INCLUDE' => 62,
			"(" => 22,
			'NOT' => 60,
			'MACRO' => 21,
			"\${" => 57,
			"{" => 56,
			"\"" => 20,
			'CLEAR' => 27,
			'META' => 65,
			"[" => 26,
			'DEBUG' => 63,
			'RETURN' => 48,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'BLOCK' => 46,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'DEFAULT' => 54,
			'rawperl' => 18,
			'LITERAL' => 50,
			'FILTER' => 16,
			'IDENT' => 15,
			'SWITCH' => 49,
			'VIEW' => 36,
			'USE' => 37,
			'STOP' => 5,
			'GET' => 35,
			'WHILE' => 2,
			'UNLESS' => 3,
			'REF' => 34,
			'NUMBER' => 10,
			'FOR' => 43,
			'TEXT' => 42,
			'PROCESS' => 9,
			'LAST' => 41,
			'RAW' => 39,
			'perl' => 7
		},
		DEFAULT => -3,
		GOTOS => {
			'macro' => 38,
			'directive' => 6,
			'setlist' => 23,
			'chunk' => 59,
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'raw' => 66,
			'item' => 40,
			'ident' => 28,
			'wrapper' => 8,
			'block' => 327,
			'atomexpr' => 25,
			'anonblock' => 24,
			'view' => 47,
			'defblock' => 29,
			'filter' => 69,
			'capture' => 11,
			'chunks' => 68,
			'defblockname' => 67,
			'term' => 55,
			'use' => 19,
			'sterm' => 53,
			'statement' => 75,
			'assign' => 52,
			'lterm' => 72,
			'loop' => 17,
			'condition' => 71,
			'expr' => 32,
			'atomdir' => 14,
			'try' => 70
		}
	},
	{#State 308
		ACTIONS => {
			'DOT' => 179,
			";" => 328
		}
	},
	{#State 309
		ACTIONS => {
			'rawperl' => 18,
			'DEFAULT' => 54,
			'IDENT' => 15,
			'SWITCH' => 49,
			'FILTER' => 16,
			'LITERAL' => 50,
			'WRAPPER' => 13,
			'BLOCK' => 46,
			'INSERT' => 12,
			'RETURN' => 48,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'LAST' => 41,
			'PROCESS' => 9,
			'TEXT' => 42,
			'FOR' => 43,
			'NUMBER' => 10,
			'perl' => 7,
			'RAW' => 39,
			'VIEW' => 36,
			'USE' => 37,
			'UNLESS' => 3,
			'WHILE' => 2,
			'REF' => 34,
			'GET' => 35,
			'STOP' => 5,
			";" => -19,
			'SET' => 73,
			"\$" => 33,
			'CALL' => 74,
			'NEXT' => 31,
			'IF' => 30,
			'DEBUG' => 63,
			"[" => 26,
			'CLEAR' => 27,
			'META' => 65,
			'MACRO' => 21,
			"(" => 22,
			'NOT' => 60,
			'INCLUDE' => 62,
			'THROW' => 61,
			"{" => 56,
			"\"" => 20,
			"\${" => 57
		},
		DEFAULT => -3,
		GOTOS => {
			'view' => 47,
			'defblock' => 29,
			'defblockname' => 67,
			'capture' => 11,
			'chunks' => 68,
			'filter' => 69,
			'statement' => 75,
			'lterm' => 72,
			'assign' => 52,
			'term' => 55,
			'use' => 19,
			'sterm' => 53,
			'try' => 70,
			'atomdir' => 14,
			'condition' => 71,
			'expr' => 32,
			'loop' => 17,
			'chunk' => 59,
			'macro' => 38,
			'setlist' => 23,
			'directive' => 6,
			'node' => 1,
			'switch' => 4,
			'javascript' => 58,
			'raw' => 66,
			'ident' => 28,
			'item' => 40,
			'block' => 329,
			'atomexpr' => 25,
			'anonblock' => 24,
			'wrapper' => 8
		}
	},
	{#State 310
		ACTIONS => {
			";" => 330
		}
	},
	{#State 311
		DEFAULT => -80
	},
	{#State 312
		DEFAULT => -89
	},
	{#State 313
		ACTIONS => {
			"\"" => 331
		}
	},
	{#State 314
		ACTIONS => {
			'END' => 332
		}
	},
	{#State 315
		ACTIONS => {
			"\${" => 57,
			'REF' => 34,
			"{" => 56,
			"\"" => 20,
			'NUMBER' => 10,
			'DEFAULT' => 334,
			"\$" => 33,
			";" => 335,
			'LITERAL' => 78,
			"[" => 26,
			'IDENT' => 15
		},
		GOTOS => {
			'node' => 1,
			'item' => 40,
			'lterm' => 72,
			'ident' => 77,
			'term' => 333,
			'sterm' => 53
		}
	},
	{#State 316
		DEFAULT => -83
	},
	{#State 317
		DEFAULT => -62
	},
	{#State 318
		ACTIONS => {
			'CMPOP' => 129,
			"/" => 125,
			'CAT' => 127,
			'MOD' => 131,
			"?" => 124,
			"+" => 128,
			'OR' => 130,
			'BINOP' => 132,
			'AND' => 133,
			";" => 336,
			'DIV' => 126
		}
	},
	{#State 319
		ACTIONS => {
			'IF' => 30,
			'NEXT' => 31,
			"\$" => 33,
			'CALL' => 74,
			'SET' => 73,
			";" => -19,
			"\${" => 57,
			"{" => 56,
			"\"" => 20,
			'THROW' => 61,
			'INCLUDE' => 62,
			'NOT' => 60,
			"(" => 22,
			'MACRO' => 21,
			'CLEAR' => 27,
			'META' => 65,
			"[" => 26,
			'DEBUG' => 63,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'RETURN' => 48,
			'INSERT' => 12,
			'BLOCK' => 46,
			'WRAPPER' => 13,
			'FILTER' => 16,
			'LITERAL' => 50,
			'SWITCH' => 49,
			'IDENT' => 15,
			'DEFAULT' => 54,
			'rawperl' => 18,
			'STOP' => 5,
			'GET' => 35,
			'REF' => 34,
			'UNLESS' => 3,
			'WHILE' => 2,
			'USE' => 37,
			'VIEW' => 36,
			'RAW' => 39,
			'perl' => 7,
			'NUMBER' => 10,
			'FOR' => 43,
			'TEXT' => 42,
			'PROCESS' => 9,
			'LAST' => 41
		},
		DEFAULT => -3,
		GOTOS => {
			'condition' => 71,
			'loop' => 17,
			'expr' => 32,
			'try' => 70,
			'atomdir' => 14,
			'sterm' => 53,
			'use' => 19,
			'term' => 55,
			'assign' => 52,
			'lterm' => 72,
			'statement' => 75,
			'filter' => 69,
			'capture' => 11,
			'defblockname' => 67,
			'chunks' => 68,
			'defblock' => 29,
			'view' => 47,
			'wrapper' => 8,
			'anonblock' => 24,
			'block' => 337,
			'atomexpr' => 25,
			'ident' => 28,
			'item' => 40,
			'raw' => 66,
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'directive' => 6,
			'setlist' => 23,
			'macro' => 38,
			'chunk' => 59
		}
	},
	{#State 320
		DEFAULT => -48
	},
	{#State 321
		ACTIONS => {
			'CAT' => 127,
			"+" => 128,
			'MOD' => 131,
			'OR' => 130,
			'AND' => 133,
			'DIV' => 126,
			'CMPOP' => 129,
			"/" => 125,
			"?" => 124,
			'BINOP' => 132
		},
		DEFAULT => -155
	},
	{#State 322
		DEFAULT => -91
	},
	{#State 323
		DEFAULT => -94
	},
	{#State 324
		DEFAULT => -46
	},
	{#State 325
		DEFAULT => -78
	},
	{#State 326
		DEFAULT => -59
	},
	{#State 327
		DEFAULT => -73
	},
	{#State 328
		ACTIONS => {
			'WHILE' => 2,
			'REF' => 34,
			'UNLESS' => 3,
			'GET' => 35,
			'STOP' => 5,
			'USE' => 37,
			'VIEW' => 36,
			'perl' => 7,
			'RAW' => 39,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'FOR' => 43,
			'NUMBER' => 10,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'BLOCK' => 46,
			'INSERT' => 12,
			'WRAPPER' => 13,
			'RETURN' => 48,
			'SWITCH' => 49,
			'IDENT' => 15,
			'LITERAL' => 50,
			'FILTER' => 16,
			'rawperl' => 18,
			'DEFAULT' => 54,
			"{" => 56,
			"\"" => 20,
			"\${" => 57,
			'MACRO' => 21,
			'NOT' => 60,
			"(" => 22,
			'THROW' => 61,
			'INCLUDE' => 62,
			'DEBUG' => 63,
			"[" => 26,
			'CLEAR' => 27,
			'META' => 65,
			'IF' => 30,
			'NEXT' => 31,
			";" => -19,
			'CALL' => 74,
			"\$" => 33,
			'SET' => 73
		},
		DEFAULT => -3,
		GOTOS => {
			'ident' => 28,
			'item' => 40,
			'raw' => 66,
			'wrapper' => 8,
			'block' => 338,
			'atomexpr' => 25,
			'anonblock' => 24,
			'directive' => 6,
			'setlist' => 23,
			'macro' => 38,
			'chunk' => 59,
			'javascript' => 58,
			'node' => 1,
			'switch' => 4,
			'sterm' => 53,
			'use' => 19,
			'term' => 55,
			'assign' => 52,
			'lterm' => 72,
			'statement' => 75,
			'condition' => 71,
			'expr' => 32,
			'loop' => 17,
			'atomdir' => 14,
			'try' => 70,
			'defblock' => 29,
			'view' => 47,
			'filter' => 69,
			'defblockname' => 67,
			'capture' => 11,
			'chunks' => 68
		}
	},
	{#State 329
		ACTIONS => {
			'CATCH' => 278,
			'FINAL' => 277
		},
		DEFAULT => -74,
		GOTOS => {
			'final' => 339
		}
	},
	{#State 330
		ACTIONS => {
			'FILTER' => 16,
			'LITERAL' => 50,
			'SWITCH' => 49,
			'IDENT' => 15,
			'DEFAULT' => 54,
			'rawperl' => 18,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'RETURN' => 48,
			'BLOCK' => 46,
			'INSERT' => 12,
			'WRAPPER' => 13,
			'RAW' => 39,
			'perl' => 7,
			'NUMBER' => 10,
			'FOR' => 43,
			'PROCESS' => 9,
			'TEXT' => 42,
			'LAST' => 41,
			'STOP' => 5,
			'GET' => 35,
			'WHILE' => 2,
			'REF' => 34,
			'UNLESS' => 3,
			'VIEW' => 36,
			'USE' => 37,
			'NEXT' => 31,
			"\$" => 33,
			'CALL' => 74,
			'SET' => 73,
			";" => -19,
			'IF' => 30,
			'META' => 65,
			'CLEAR' => 27,
			"[" => 26,
			'DEBUG' => 63,
			"\${" => 57,
			"\"" => 20,
			"{" => 56,
			'THROW' => 61,
			'INCLUDE' => 62,
			'NOT' => 60,
			"(" => 22,
			'MACRO' => 21
		},
		DEFAULT => -3,
		GOTOS => {
			'javascript' => 58,
			'node' => 1,
			'switch' => 4,
			'macro' => 38,
			'directive' => 6,
			'setlist' => 23,
			'chunk' => 59,
			'wrapper' => 8,
			'atomexpr' => 25,
			'block' => 340,
			'anonblock' => 24,
			'raw' => 66,
			'ident' => 28,
			'item' => 40,
			'filter' => 69,
			'chunks' => 68,
			'defblockname' => 67,
			'capture' => 11,
			'view' => 47,
			'defblock' => 29,
			'condition' => 71,
			'loop' => 17,
			'expr' => 32,
			'atomdir' => 14,
			'try' => 70,
			'term' => 55,
			'use' => 19,
			'sterm' => 53,
			'statement' => 75,
			'assign' => 52,
			'lterm' => 72
		}
	},
	{#State 331
		DEFAULT => -102
	},
	{#State 332
		DEFAULT => -53
	},
	{#State 333
		ACTIONS => {
			";" => 341
		}
	},
	{#State 334
		ACTIONS => {
			";" => 342
		}
	},
	{#State 335
		ACTIONS => {
			'rawperl' => 18,
			'DEFAULT' => 54,
			'IDENT' => 15,
			'SWITCH' => 49,
			'LITERAL' => 50,
			'FILTER' => 16,
			'INSERT' => 12,
			'WRAPPER' => 13,
			'BLOCK' => 46,
			'RETURN' => 48,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'FOR' => 43,
			'NUMBER' => 10,
			'perl' => 7,
			'RAW' => 39,
			'USE' => 37,
			'VIEW' => 36,
			'UNLESS' => 3,
			'REF' => 34,
			'WHILE' => 2,
			'GET' => 35,
			'STOP' => 5,
			";" => -19,
			"\$" => 33,
			'CALL' => 74,
			'SET' => 73,
			'NEXT' => 31,
			'IF' => 30,
			'DEBUG' => 63,
			"[" => 26,
			'CLEAR' => 27,
			'META' => 65,
			'MACRO' => 21,
			"(" => 22,
			'NOT' => 60,
			'INCLUDE' => 62,
			'THROW' => 61,
			"\"" => 20,
			"{" => 56,
			"\${" => 57
		},
		DEFAULT => -3,
		GOTOS => {
			'capture' => 11,
			'chunks' => 68,
			'defblockname' => 67,
			'filter' => 69,
			'view' => 47,
			'defblock' => 29,
			'try' => 70,
			'atomdir' => 14,
			'expr' => 32,
			'loop' => 17,
			'condition' => 71,
			'statement' => 75,
			'assign' => 52,
			'lterm' => 72,
			'term' => 55,
			'sterm' => 53,
			'use' => 19,
			'switch' => 4,
			'node' => 1,
			'javascript' => 58,
			'chunk' => 59,
			'macro' => 38,
			'setlist' => 23,
			'directive' => 6,
			'atomexpr' => 25,
			'anonblock' => 24,
			'block' => 343,
			'wrapper' => 8,
			'raw' => 66,
			'item' => 40,
			'ident' => 28
		}
	},
	{#State 336
		ACTIONS => {
			'NEXT' => 31,
			'SET' => 73,
			"\$" => 33,
			'CALL' => 74,
			";" => -19,
			'IF' => 30,
			'META' => 65,
			'CLEAR' => 27,
			"[" => 26,
			'DEBUG' => 63,
			"\${" => 57,
			"\"" => 20,
			"{" => 56,
			'THROW' => 61,
			'INCLUDE' => 62,
			'NOT' => 60,
			"(" => 22,
			'MACRO' => 21,
			'LITERAL' => 50,
			'FILTER' => 16,
			'IDENT' => 15,
			'SWITCH' => 49,
			'DEFAULT' => 54,
			'rawperl' => 18,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'RETURN' => 48,
			'INSERT' => 12,
			'WRAPPER' => 13,
			'BLOCK' => 46,
			'RAW' => 39,
			'perl' => 7,
			'NUMBER' => 10,
			'FOR' => 43,
			'PROCESS' => 9,
			'TEXT' => 42,
			'LAST' => 41,
			'STOP' => 5,
			'GET' => 35,
			'UNLESS' => 3,
			'REF' => 34,
			'WHILE' => 2,
			'USE' => 37,
			'VIEW' => 36
		},
		DEFAULT => -3,
		GOTOS => {
			'chunks' => 68,
			'capture' => 11,
			'defblockname' => 67,
			'filter' => 69,
			'view' => 47,
			'defblock' => 29,
			'try' => 70,
			'atomdir' => 14,
			'loop' => 17,
			'expr' => 32,
			'condition' => 71,
			'statement' => 75,
			'assign' => 52,
			'lterm' => 72,
			'term' => 55,
			'use' => 19,
			'sterm' => 53,
			'switch' => 4,
			'node' => 1,
			'javascript' => 58,
			'chunk' => 59,
			'macro' => 38,
			'setlist' => 23,
			'directive' => 6,
			'atomexpr' => 25,
			'block' => 344,
			'anonblock' => 24,
			'wrapper' => 8,
			'raw' => 66,
			'ident' => 28,
			'item' => 40
		}
	},
	{#State 337
		DEFAULT => -51
	},
	{#State 338
		ACTIONS => {
			'FINAL' => 277,
			'CATCH' => 278
		},
		DEFAULT => -74,
		GOTOS => {
			'final' => 345
		}
	},
	{#State 339
		DEFAULT => -72
	},
	{#State 340
		ACTIONS => {
			'FINAL' => 277,
			'CATCH' => 278
		},
		DEFAULT => -74,
		GOTOS => {
			'final' => 346
		}
	},
	{#State 341
		ACTIONS => {
			'rawperl' => 18,
			'DEFAULT' => 54,
			'SWITCH' => 49,
			'IDENT' => 15,
			'FILTER' => 16,
			'LITERAL' => 50,
			'WRAPPER' => 13,
			'INSERT' => 12,
			'BLOCK' => 46,
			'RETURN' => 48,
			'TRY' => 44,
			'JAVASCRIPT' => 45,
			'LAST' => 41,
			'PROCESS' => 9,
			'TEXT' => 42,
			'FOR' => 43,
			'NUMBER' => 10,
			'perl' => 7,
			'RAW' => 39,
			'USE' => 37,
			'VIEW' => 36,
			'UNLESS' => 3,
			'REF' => 34,
			'WHILE' => 2,
			'GET' => 35,
			'STOP' => 5,
			";" => -19,
			'CALL' => 74,
			"\$" => 33,
			'SET' => 73,
			'NEXT' => 31,
			'IF' => 30,
			'DEBUG' => 63,
			"[" => 26,
			'META' => 65,
			'CLEAR' => 27,
			'MACRO' => 21,
			"(" => 22,
			'NOT' => 60,
			'INCLUDE' => 62,
			'THROW' => 61,
			"\"" => 20,
			"{" => 56,
			"\${" => 57
		},
		DEFAULT => -3,
		GOTOS => {
			'javascript' => 58,
			'switch' => 4,
			'node' => 1,
			'macro' => 38,
			'setlist' => 23,
			'directive' => 6,
			'chunk' => 59,
			'wrapper' => 8,
			'block' => 347,
			'anonblock' => 24,
			'atomexpr' => 25,
			'raw' => 66,
			'ident' => 28,
			'item' => 40,
			'filter' => 69,
			'capture' => 11,
			'chunks' => 68,
			'defblockname' => 67,
			'view' => 47,
			'defblock' => 29,
			'loop' => 17,
			'expr' => 32,
			'condition' => 71,
			'atomdir' => 14,
			'try' => 70,
			'term' => 55,
			'use' => 19,
			'sterm' => 53,
			'statement' => 75,
			'lterm' => 72,
			'assign' => 52
		}
	},
	{#State 342
		ACTIONS => {
			'USE' => 37,
			'VIEW' => 36,
			'STOP' => 5,
			'REF' => 34,
			'WHILE' => 2,
			'UNLESS' => 3,
			'GET' => 35,
			'FOR' => 43,
			'NUMBER' => 10,
			'LAST' => 41,
			'TEXT' => 42,
			'PROCESS' => 9,
			'perl' => 7,
			'RAW' => 39,
			'RETURN' => 48,
			'WRAPPER' => 13,
			'BLOCK' => 46,
			'INSERT' => 12,
			'JAVASCRIPT' => 45,
			'TRY' => 44,
			'DEFAULT' => 54,
			'rawperl' => 18,
			'LITERAL' => 50,
			'FILTER' => 16,
			'SWITCH' => 49,
			'IDENT' => 15,
			'NOT' => 60,
			"(" => 22,
			'THROW' => 61,
			'INCLUDE' => 62,
			'MACRO' => 21,
			"\${" => 57,
			"\"" => 20,
			"{" => 56,
			"[" => 26,
			'META' => 65,
			'CLEAR' => 27,
			'DEBUG' => 63,
			'IF' => 30,
			";" => -19,
			'SET' => 73,
			'CALL' => 74,
			"\$" => 33,
			'NEXT' => 31
		},
		DEFAULT => -3,
		GOTOS => {
			'atomdir' => 14,
			'try' => 70,
			'condition' => 71,
			'loop' => 17,
			'expr' => 32,
			'assign' => 52,
			'lterm' => 72,
			'statement' => 75,
			'sterm' => 53,
			'use' => 19,
			'term' => 55,
			'capture' => 11,
			'defblockname' => 67,
			'chunks' => 68,
			'filter' => 69,
			'defblock' => 29,
			'view' => 47,
			'block' => 348,
			'atomexpr' => 25,
			'anonblock' => 24,
			'wrapper' => 8,
			'ident' => 28,
			'item' => 40,
			'raw' => 66,
			'switch' => 4,
			'node' => 1,
			'javascript' => 58,
			'chunk' => 59,
			'setlist' => 23,
			'directive' => 6,
			'macro' => 38
		}
	},
	{#State 343
		DEFAULT => -56
	},
	{#State 344
		ACTIONS => {
			'ELSIF' => 289,
			'ELSE' => 290
		},
		DEFAULT => -52,
		GOTOS => {
			'else' => 349
		}
	},
	{#State 345
		DEFAULT => -70
	},
	{#State 346
		DEFAULT => -71
	},
	{#State 347
		ACTIONS => {
			'CASE' => 315
		},
		DEFAULT => -57,
		GOTOS => {
			'case' => 350
		}
	},
	{#State 348
		DEFAULT => -55
	},
	{#State 349
		DEFAULT => -50
	},
	{#State 350
		DEFAULT => -54
	}
]; 


#========================================================================
# Rules
#========================================================================

$RULES = [
	[#Rule 0
		 '$start', 2, undef
	],
	[#Rule 1
		 'template', 1,
sub
#line 68 "Parser.yp"
{ $factory->template($_[1])           }
	],
	[#Rule 2
		 'block', 1,
sub
#line 71 "Parser.yp"
{ $factory->block($_[1])              }
	],
	[#Rule 3
		 'block', 0,
sub
#line 72 "Parser.yp"
{ $factory->block()                   }
	],
	[#Rule 4
		 'chunks', 2,
sub
#line 75 "Parser.yp"
{ push(@{$_[1]}, $_[2]) 
					if defined $_[2]; $_[1]           }
	],
	[#Rule 5
		 'chunks', 1,
sub
#line 77 "Parser.yp"
{ defined $_[1] ? [ $_[1] ] : [ ]     }
	],
	[#Rule 6
		 'chunk', 1,
sub
#line 80 "Parser.yp"
{ $factory->textblock($_[1])          }
	],
	[#Rule 7
		 'chunk', 2,
sub
#line 81 "Parser.yp"
{ return '' unless $_[1];
                           $_[0]->location() . $_[1];
                         }
	],
	[#Rule 8
		 'statement', 1, undef
	],
	[#Rule 9
		 'statement', 1, undef
	],
	[#Rule 10
		 'statement', 1, undef
	],
	[#Rule 11
		 'statement', 1, undef
	],
	[#Rule 12
		 'statement', 1, undef
	],
	[#Rule 13
		 'statement', 1, undef
	],
	[#Rule 14
		 'statement', 1, undef
	],
	[#Rule 15
		 'statement', 1, undef
	],
	[#Rule 16
		 'statement', 1, undef
	],
	[#Rule 17
		 'statement', 1,
sub
#line 95 "Parser.yp"
{ $factory->get($_[1])                }
	],
	[#Rule 18
		 'statement', 2,
sub
#line 96 "Parser.yp"
{ $_[0]->add_metadata($_[2]);         }
	],
	[#Rule 19
		 'statement', 0, undef
	],
	[#Rule 20
		 'directive', 1,
sub
#line 100 "Parser.yp"
{ $factory->set($_[1])                }
	],
	[#Rule 21
		 'directive', 1, undef
	],
	[#Rule 22
		 'directive', 1, undef
	],
	[#Rule 23
		 'directive', 1, undef
	],
	[#Rule 24
		 'directive', 1, undef
	],
	[#Rule 25
		 'directive', 1, undef
	],
	[#Rule 26
		 'directive', 1, undef
	],
	[#Rule 27
		 'directive', 1, undef
	],
	[#Rule 28
		 'atomexpr', 1,
sub
#line 115 "Parser.yp"
{ $factory->get($_[1])                }
	],
	[#Rule 29
		 'atomexpr', 1, undef
	],
	[#Rule 30
		 'atomdir', 2,
sub
#line 119 "Parser.yp"
{ $factory->get($_[2])                }
	],
	[#Rule 31
		 'atomdir', 2,
sub
#line 120 "Parser.yp"
{ $factory->call($_[2])               }
	],
	[#Rule 32
		 'atomdir', 2,
sub
#line 121 "Parser.yp"
{ $factory->set($_[2])                }
	],
	[#Rule 33
		 'atomdir', 2,
sub
#line 122 "Parser.yp"
{ $factory->default($_[2])            }
	],
	[#Rule 34
		 'atomdir', 2,
sub
#line 123 "Parser.yp"
{ $factory->insert($_[2])             }
	],
	[#Rule 35
		 'atomdir', 2,
sub
#line 124 "Parser.yp"
{ $factory->include($_[2])            }
	],
	[#Rule 36
		 'atomdir', 2,
sub
#line 125 "Parser.yp"
{ $factory->process($_[2])            }
	],
	[#Rule 37
		 'atomdir', 2,
sub
#line 126 "Parser.yp"
{ $factory->throw($_[2])              }
	],
	[#Rule 38
		 'atomdir', 1,
sub
#line 127 "Parser.yp"
{ $factory->return()                  }
	],
	[#Rule 39
		 'atomdir', 1,
sub
#line 128 "Parser.yp"
{ $factory->stop()                    }
	],
	[#Rule 40
		 'atomdir', 1,
sub
#line 129 "Parser.yp"
{ $factory->clear()                   }
	],
	[#Rule 41
		 'atomdir', 1,
sub
#line 130 "Parser.yp"
{ $factory->break()                   }
	],
	[#Rule 42
		 'atomdir', 1,
sub
#line 131 "Parser.yp"
{ $factory->next()                    }
	],
	[#Rule 43
		 'atomdir', 2,
sub
#line 132 "Parser.yp"
{ if ($_[2]->[0]->[0] =~ /^'(on|off)'$/) {
				          $_[0]->{ DEBUG_DIRS } = ($1 eq 'on');
					  $factory->debug($_[2]);
				      }
				      else {
					  $_[0]->{ DEBUG_DIRS } ? $factory->debug($_[2]) : '';
				      }
				    }
	],
	[#Rule 44
		 'atomdir', 1, undef
	],
	[#Rule 45
		 'atomdir', 1, undef
	],
	[#Rule 46
		 'condition', 6,
sub
#line 145 "Parser.yp"
{ $factory->if(@_[2, 4, 5])           }
	],
	[#Rule 47
		 'condition', 3,
sub
#line 146 "Parser.yp"
{ $factory->if(@_[3, 1])              }
	],
	[#Rule 48
		 'condition', 6,
sub
#line 148 "Parser.yp"
{ $factory->if("tt2_not($_[2])", @_[4, 5])  }
	],
	[#Rule 49
		 'condition', 3,
sub
#line 149 "Parser.yp"
{ $factory->if("tt2_not($_[3])", $_[1])     }
	],
	[#Rule 50
		 'else', 5,
sub
#line 153 "Parser.yp"
{ unshift(@{$_[5]}, [ @_[2, 4] ]);
				      $_[5];                              }
	],
	[#Rule 51
		 'else', 3,
sub
#line 155 "Parser.yp"
{ [ $_[3] ]                           }
	],
	[#Rule 52
		 'else', 0,
sub
#line 156 "Parser.yp"
{ [ undef ]                           }
	],
	[#Rule 53
		 'switch', 6,
sub
#line 160 "Parser.yp"
{ $factory->switch(@_[2, 5])          }
	],
	[#Rule 54
		 'case', 5,
sub
#line 164 "Parser.yp"
{ unshift(@{$_[5]}, [ @_[2, 4] ]); 
				      $_[5];                              }
	],
	[#Rule 55
		 'case', 4,
sub
#line 166 "Parser.yp"
{ [ $_[4] ]                           }
	],
	[#Rule 56
		 'case', 3,
sub
#line 167 "Parser.yp"
{ [ $_[3] ]                           }
	],
	[#Rule 57
		 'case', 0,
sub
#line 168 "Parser.yp"
{ [ undef ]                           }
	],
	[#Rule 58
		 '@1-3', 0,
sub
#line 171 "Parser.yp"
{ $_[0]->{ INFOR }++                  }
	],
	[#Rule 59
		 'loop', 6,
sub
#line 172 "Parser.yp"
{ $_[0]->{ INFOR }--;
				      $factory->foreach(@{$_[2]}, $_[5])  }
	],
	[#Rule 60
		 'loop', 3,
sub
#line 176 "Parser.yp"
{ $factory->foreach(@{$_[3]}, $_[1])  }
	],
	[#Rule 61
		 '@2-3', 0,
sub
#line 177 "Parser.yp"
{ $_[0]->{ INWHILE }++                }
	],
	[#Rule 62
		 'loop', 6,
sub
#line 178 "Parser.yp"
{ $_[0]->{ INWHILE }--;
                                      $factory->while(@_[2, 5])           }
	],
	[#Rule 63
		 'loop', 3,
sub
#line 180 "Parser.yp"
{ $factory->while(@_[3, 1])           }
	],
	[#Rule 64
		 'loopvar', 4,
sub
#line 183 "Parser.yp"
{ [ @_[1, 3, 4] ]                     }
	],
	[#Rule 65
		 'loopvar', 4,
sub
#line 184 "Parser.yp"
{ [ @_[1, 3, 4] ]                     }
	],
	[#Rule 66
		 'loopvar', 2,
sub
#line 185 "Parser.yp"
{ [ 0, @_[1, 2] ]                     }
	],
	[#Rule 67
		 'wrapper', 5,
sub
#line 189 "Parser.yp"
{ $factory->wrapper(@_[2, 4])         }
	],
	[#Rule 68
		 'wrapper', 3,
sub
#line 191 "Parser.yp"
{ $factory->wrapper(@_[3, 1])         }
	],
	[#Rule 69
		 'try', 5,
sub
#line 195 "Parser.yp"
{ $factory->try(@_[3, 4])             }
	],
	[#Rule 70
		 'final', 5,
sub
#line 199 "Parser.yp"
{ unshift(@{$_[5]}, [ @_[2,4] ]);
				      $_[5];                              }
	],
	[#Rule 71
		 'final', 5,
sub
#line 202 "Parser.yp"
{ unshift(@{$_[5]}, [ undef, $_[4] ]);
				      $_[5];                              }
	],
	[#Rule 72
		 'final', 4,
sub
#line 205 "Parser.yp"
{ unshift(@{$_[4]}, [ undef, $_[3] ]);
				      $_[4];                              }
	],
	[#Rule 73
		 'final', 3,
sub
#line 207 "Parser.yp"
{ [ $_[3] ]                           }
	],
	[#Rule 74
		 'final', 0,
sub
#line 208 "Parser.yp"
{ [ 0 ] }
	],
	[#Rule 75
		 'use', 2,
sub
#line 211 "Parser.yp"
{ $factory->use($_[2])                }
	],
	[#Rule 76
		 'raw', 2,
sub
#line 214 "Parser.yp"
{ $factory->raw($_[2])                }
	],
	[#Rule 77
		 '@3-3', 0,
sub
#line 217 "Parser.yp"
{ $_[0]->push_defblock();		  }
	],
	[#Rule 78
		 'view', 6,
sub
#line 218 "Parser.yp"
{ $factory->view(@_[2,5], 
						     $_[0]->pop_defblock) }
	],
	[#Rule 79
		 '@4-2', 0,
sub
#line 222 "Parser.yp"
{ ${$_[0]->{ INJAVASCRIPT }}++;             }
	],
	[#Rule 80
		 'javascript', 5,
sub
#line 223 "Parser.yp"
{ ${$_[0]->{ INJAVASCRIPT }}--;
				      $_[0]->{ EVAL_JAVASCRIPT } 
				      ? $factory->javascript($_[4])             
				      : $factory->no_javascript();              }
	],
	[#Rule 81
		 'filter', 5,
sub
#line 230 "Parser.yp"
{ $factory->filter(@_[2,4])           }
	],
	[#Rule 82
		 'filter', 3,
sub
#line 232 "Parser.yp"
{ $factory->filter(@_[3,1])           }
	],
	[#Rule 83
		 'defblock', 5,
sub
#line 237 "Parser.yp"
{ my $name = join('/', @{ $_[0]->{ DEFBLOCKS } });
				      pop(@{ $_[0]->{ DEFBLOCKS } });
				      $_[0]->define_block($name, $_[4]); 
				      undef
				    }
	],
	[#Rule 84
		 'defblockname', 2,
sub
#line 244 "Parser.yp"
{ push(@{ $_[0]->{ DEFBLOCKS } }, $_[2]);
				      $_[2];
				    }
	],
	[#Rule 85
		 'blockname', 1, undef
	],
	[#Rule 86
		 'blockname', 1,
sub
#line 250 "Parser.yp"
{ $_[1] =~ s/^'(.*)'$/$1/; $_[1]      }
	],
	[#Rule 87
		 'blockargs', 1, undef
	],
	[#Rule 88
		 'blockargs', 0, undef
	],
	[#Rule 89
		 'anonblock', 5,
sub
#line 258 "Parser.yp"
{ local $" = ', ';
				      print STDERR "experimental block args: [@{ $_[2] }]\n"
					  if $_[2];
				      $factory->anon_block($_[4])         }
	],
	[#Rule 90
		 'capture', 3,
sub
#line 264 "Parser.yp"
{ $factory->capture(@_[1, 3])         }
	],
	[#Rule 91
		 'macro', 6,
sub
#line 268 "Parser.yp"
{ $factory->macro(@_[2, 6, 4])        }
	],
	[#Rule 92
		 'macro', 3,
sub
#line 269 "Parser.yp"
{ $factory->macro(@_[2, 3])           }
	],
	[#Rule 93
		 'mdir', 1, undef
	],
	[#Rule 94
		 'mdir', 4,
sub
#line 273 "Parser.yp"
{ $_[3]                               }
	],
	[#Rule 95
		 'margs', 2,
sub
#line 276 "Parser.yp"
{ push(@{$_[1]}, $_[2]); $_[1]        }
	],
	[#Rule 96
		 'margs', 2,
sub
#line 277 "Parser.yp"
{ $_[1]                               }
	],
	[#Rule 97
		 'margs', 1,
sub
#line 278 "Parser.yp"
{ [ $_[1] ]                           }
	],
	[#Rule 98
		 'metadata', 2,
sub
#line 281 "Parser.yp"
{ push(@{$_[1]}, @{$_[2]}); $_[1]     }
	],
	[#Rule 99
		 'metadata', 2, undef
	],
	[#Rule 100
		 'metadata', 1, undef
	],
	[#Rule 101
		 'meta', 3,
sub
#line 286 "Parser.yp"
{ for ($_[3]) { s/^'//; s/'$//; 
						       s/\\'/'/g  }; 
					 [ @_[1,3] ] }
	],
	[#Rule 102
		 'meta', 5,
sub
#line 289 "Parser.yp"
{ [ @_[1,4] ] }
	],
	[#Rule 103
		 'meta', 3,
sub
#line 290 "Parser.yp"
{ [ @_[1,3] ] }
	],
	[#Rule 104
		 'term', 1, undef
	],
	[#Rule 105
		 'term', 1, undef
	],
	[#Rule 106
		 'lterm', 3,
sub
#line 302 "Parser.yp"
{ "{ $_[2] }"                         }
	],
	[#Rule 107
		 'lterm', 3,
sub
#line 303 "Parser.yp"
{ "{ $_[2] }"                         }
	],
	[#Rule 108
		 'lterm', 2,
sub
#line 304 "Parser.yp"
{ "{ }"                               }
	],
	[#Rule 109
		 'lterm', 3,
sub
#line 305 "Parser.yp"
{ "{ $_[2]  }"                        }
	],
	[#Rule 110
		 'sterm', 1,
sub
#line 308 "Parser.yp"
{ $factory->ident($_[1])              }
	],
	[#Rule 111
		 'sterm', 2,
sub
#line 309 "Parser.yp"
{ $factory->identref($_[2])           }
	],
	[#Rule 112
		 'sterm', 3,
sub
#line 310 "Parser.yp"
{ $factory->quoted($_[2])             }
	],
	[#Rule 113
		 'sterm', 1, undef
	],
	[#Rule 114
		 'sterm', 1, undef
	],
	[#Rule 115
		 'list', 2,
sub
#line 315 "Parser.yp"
{ "$_[1], $_[2]"                      }
	],
	[#Rule 116
		 'list', 2, undef
	],
	[#Rule 117
		 'list', 1, undef
	],
	[#Rule 118
		 'range', 3,
sub
#line 320 "Parser.yp"
{ $_[1] . '..' . $_[3]                }
	],
	[#Rule 119
		 'hash', 1, undef
	],
	[#Rule 120
		 'hash', 0,
sub
#line 325 "Parser.yp"
{ "" }
	],
	[#Rule 121
		 'params', 2,
sub
#line 328 "Parser.yp"
{ "$_[1], $_[2]"                      }
	],
	[#Rule 122
		 'params', 2, undef
	],
	[#Rule 123
		 'params', 1, undef
	],
	[#Rule 124
		 'param', 3,
sub
#line 333 "Parser.yp"
{ "[$_[1]] = $_[3]"                    }
	],
	[#Rule 125
		 'param', 3,
sub
#line 334 "Parser.yp"
{ "[$_[1]] = $_[3]"                    }
	],
	[#Rule 126
		 'ident', 3,
sub
#line 337 "Parser.yp"
{ push(@{$_[1]}, @{$_[3]}); $_[1]     }
	],
	[#Rule 127
		 'ident', 3,
sub
#line 338 "Parser.yp"
{ push(@{$_[1]}, 
					   map {($_, 0)} split(/\./, $_[3]));
				      $_[1];			          }
	],
	[#Rule 128
		 'ident', 1, undef
	],
	[#Rule 129
		 'node', 1,
sub
#line 344 "Parser.yp"
{ [ $_[1], 0 ]                        }
	],
	[#Rule 130
		 'node', 4,
sub
#line 345 "Parser.yp"
{ [ $_[1], $factory->args($_[3]) ]    }
	],
	[#Rule 131
		 'item', 1,
sub
#line 348 "Parser.yp"
{ "'$_[1]'"                           }
	],
	[#Rule 132
		 'item', 3,
sub
#line 349 "Parser.yp"
{ $_[2]                               }
	],
	[#Rule 133
		 'item', 2,
sub
#line 350 "Parser.yp"
{ $_[0]->{ V1DOLLAR }
				       ? "'$_[2]'" 
				       : $factory->ident(["'$_[2]'", 0])  }
	],
	[#Rule 134
		 'expr', 3,
sub
#line 355 "Parser.yp"
{ "$_[1] $_[2] $_[3]"                 }
	],
	[#Rule 135
		 'expr', 3,
sub
#line 356 "Parser.yp"
{ "$_[1] $_[2] $_[3]"                 }
	],
	[#Rule 136
		 'expr', 3,
sub
#line 357 "Parser.yp"
{ "$_[1] $_[2] $_[3]"                 }
	],
	[#Rule 137
		 'expr', 3,
sub
#line 358 "Parser.yp"
{ "math_floor($_[1] / $_[3])"         }
	],
	[#Rule 138
		 'expr', 3,
sub
#line 359 "Parser.yp"
{ "$_[1] % $_[3]"                     }
	],
	[#Rule 139
		 'expr', 3,
sub
#line 360 "Parser.yp"
{ "$_[1] $CMPOP{ $_[2] } $_[3]"       }
	],
	[#Rule 140
		 'expr', 3,
sub
#line 361 "Parser.yp"
{ "$_[1] .. $_[3]"                    }
	],
	[#Rule 141
		 'expr', 3,
sub
#line 362 "Parser.yp"
{ "tt2_true($_[1]) and tt2_true($_[3])"                   }
	],
	[#Rule 142
		 'expr', 3,
sub
#line 363 "Parser.yp"
{ "tt2_true($_[1]) or tt2_true($_[3])"                    }
	],
	[#Rule 143
		 'expr', 2,
sub
#line 364 "Parser.yp"
{ "tt2_not($_[2])"                         }
	],
	[#Rule 144
		 'expr', 5,
sub
#line 365 "Parser.yp"
{ "tt2_true($_[1]) and $_[3] or $_[5]"          }
	],
	[#Rule 145
		 'expr', 3,
sub
#line 366 "Parser.yp"
{ $factory->assign(@{$_[2]})          }
	],
	[#Rule 146
		 'expr', 3,
sub
#line 367 "Parser.yp"
{ "($_[2])"                           }
	],
	[#Rule 147
		 'expr', 1, undef
	],
	[#Rule 148
		 'setlist', 2,
sub
#line 371 "Parser.yp"
{ push(@{$_[1]}, @{$_[2]}); $_[1]     }
	],
	[#Rule 149
		 'setlist', 2, undef
	],
	[#Rule 150
		 'setlist', 1, undef
	],
	[#Rule 151
		 'assign', 3,
sub
#line 377 "Parser.yp"
{ [ $_[1], $_[3] ]                    }
	],
	[#Rule 152
		 'assign', 3,
sub
#line 378 "Parser.yp"
{ [ @_[1,3] ]                         }
	],
	[#Rule 153
		 'args', 2,
sub
#line 385 "Parser.yp"
{ push(@{$_[1]}, $_[2]); $_[1]        }
	],
	[#Rule 154
		 'args', 2,
sub
#line 386 "Parser.yp"
{ push(@{$_[1]->[0]}, $_[2]); $_[1]   }
	],
	[#Rule 155
		 'args', 4,
sub
#line 387 "Parser.yp"
{ push(@{$_[1]->[0]}, "'', " . 
				      $factory->assign(@_[2,4])); $_[1]  }
	],
	[#Rule 156
		 'args', 2,
sub
#line 389 "Parser.yp"
{ $_[1]                               }
	],
	[#Rule 157
		 'args', 0,
sub
#line 390 "Parser.yp"
{ [ [ ] ]                             }
	],
	[#Rule 158
		 'lnameargs', 3,
sub
#line 400 "Parser.yp"
{ push(@{$_[3]}, $_[1]); $_[3]        }
	],
	[#Rule 159
		 'lnameargs', 1, undef
	],
	[#Rule 160
		 'lvalue', 1, undef
	],
	[#Rule 161
		 'lvalue', 3,
sub
#line 405 "Parser.yp"
{ $factory->quoted($_[2])             }
	],
	[#Rule 162
		 'lvalue', 1, undef
	],
	[#Rule 163
		 'nameargs', 3,
sub
#line 409 "Parser.yp"
{ [ [$factory->ident($_[2])], $_[3] ]   }
	],
	[#Rule 164
		 'nameargs', 2,
sub
#line 410 "Parser.yp"
{ [ @_[1,2] ] }
	],
	[#Rule 165
		 'nameargs', 4,
sub
#line 411 "Parser.yp"
{ [ @_[1,3] ] }
	],
	[#Rule 166
		 'names', 3,
sub
#line 414 "Parser.yp"
{ push(@{$_[1]}, $_[3]); $_[1] }
	],
	[#Rule 167
		 'names', 1,
sub
#line 415 "Parser.yp"
{ [ $_[1] ]                    }
	],
	[#Rule 168
		 'name', 3,
sub
#line 418 "Parser.yp"
{ $factory->quoted($_[2])  }
	],
	[#Rule 169
		 'name', 1,
sub
#line 419 "Parser.yp"
{ "'$_[1]'" }
	],
	[#Rule 170
		 'name', 1, undef
	],
	[#Rule 171
		 'filename', 3,
sub
#line 431 "Parser.yp"
{ "$_[1].$_[3]" }
	],
	[#Rule 172
		 'filename', 1, undef
	],
	[#Rule 173
		 'filepart', 1, undef
	],
	[#Rule 174
		 'filepart', 1, undef
	],
	[#Rule 175
		 'filepart', 1, undef
	],
	[#Rule 176
		 'quoted', 2,
sub
#line 445 "Parser.yp"
{ push(@{$_[1]}, $_[2]) 
				          if defined $_[2]; $_[1]         }
	],
	[#Rule 177
		 'quoted', 0,
sub
#line 447 "Parser.yp"
{ [ ]                                 }
	],
	[#Rule 178
		 'quotable', 1,
sub
#line 450 "Parser.yp"
{ $factory->ident($_[1])              }
	],
	[#Rule 179
		 'quotable', 1,
sub
#line 451 "Parser.yp"
{ $factory->text($_[1])               }
	],
	[#Rule 180
		 'quotable', 1,
sub
#line 452 "Parser.yp"
{ undef                               }
	]
];

1;
